<img src="<?=HTTP_TEMPLATE_IMAGES?>/<?=$this->share_image?>" class="hide" />
<div class="lead_magent text-center form_field_border form_field_border_margin">
	<div class="row">
    	
        <form method="post" name="homeval_step1" id="homeval_step1" class="profile_form">
       
       	 <div class="col-md-10 col-md-offset-1 form_field">
        		<div class="row">
                  <div class="col-md-12">
        	<p class="head_style ">Learn The 5 Biggest Mistakes <?=$this->title?> Homebuyers Make When Purchasing a Home</p>
        </div>
       			 <div class="col-md-12">
        	<p class="sub">Hint: It’s Not Common Knowledge</p>
        </div>
        	 <div class="col-md-12"><?=$this->form->submitbtn?></div>
                </div>
        </div>
        </form>
    </div>
</div>

<?php if(empty($this->pop_ip_data)) {?>
<div class="modal fade bs-example-modal-lg popupmodal" data-backdrop="static" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close exitpopup" data-dismiss="modal"  aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
       	<div class="fullwidthdiv">
        	<div class="row">
            	<div class="col-md-8 col-sm-12 text-center custom8width">
                    <p class="inner_txt inner_txt_buyer">
                    	<span class="buyermistake1">DONT LEAVE EMPTY HANDED!</span>
                        <br />
                       <span class="buyermistake2">GET THE 5 BIGGEST</span>
                        <br />
                       <span class="buyermistake3">HOME BUYER MISTAKES</span>
                        <br />
                      <span class="buyermistake4">CHEAT SHEET</span>
                    </p>
                </div>
                <div class="col-md-4 col-sm-12 custom4width text-center">
                	<img  class="img-responsive" src="<?=HTTP_SITE_IMAGES?>/buyyer_mis.png" alt="mistakes" />
                </div>
            </div>
            <div class="row">
            	<div class="strike">
    				<span><img  class="img-responsive" src="<?=HTTP_SITE_IMAGES?>/hr_arrow.png" alt="report" /></span>
				</div>
            </div>
             <div class="row">
             	<div class="col-md-6  col-sm-6 text-center fullwidth">
                	<div name="yes" id="submit_popup" class="yes" >
                	<span>YES</span>
					<span class="span1 changefont1">I want to be a savvy homebuyer!</span>
                </div>
                <img  class="img-responsive" src="<?=HTTP_SITE_IMAGES?>/shadow.png" alt="shadow" />
                </div>
                <div class="col-md-6 col-sm-6 text-center">
                	<div name="no" id="no" class="no exitpopup"  data-dismiss="modal" >
                	<span>NO</span>
				<span class="span1 changefont1">I prefer to make buyer mistakes</span>
                </div>
                 <img class="img-responsive"  src="<?=HTTP_SITE_IMAGES?>/shadow.png" alt="shadow" />
                </div>
            	
                
            </div>
        </div>
      </div>
      
    </div>
  </div>
</div>
<?php }?>
<script>
$(document).ready(function(e) {
	updateSize(); 
	var lp_id='<?=$this->lp_id?>';
	lp_id=$.trim(lp_id);
	if(lp_id=='')
	{
		$('button').attr('disabled','disabled');
	}
	
});


	$(window).resize(function(e) {
		if($(window).width()!=1024)
        updateSize();
    });
	
	$('#submit_popup').click(function(e) {
    
			document.homeval_step1.submit();
    });
</script>
<script type="text/javascript">
	var closed_var='0';

$(window).load(function(e) {
		$(document).mousemove(function(e) {
			if(e.pageY <= 5)
			{
				// Show the exit popup
				<?php if(empty($this->pop_ip_data)) {?>
					var lp_id='<?=$this->lp_id?>';
					if(lp_id=='' ){}
					else if(closed_var=='0'){
					if(!$('#myModal').is(':visible'))	
					$('#myModal').appendTo("body").modal('show');
					}
				<?php } ?> 
			}
		
		});
});		
		
	$('#myModal').on('hidden.bs.modal', function (e) {
  			AddIpData(<?=$this->lp_id?>);
			closed_var='1';
		})
</script>

