
<div class="custom-form-wrapper">
  
  <div class="row">
    <div class="col-md-12 text-left temp_head oswaldfont">
      <?=$this->page_title?>
    </div>
    <div class="col-md-12">
      <form method="post" name="search_form" id="search_form"  action="<?=$this->baseUrl()?>/landingpages/allleads">

  	<div class="inner_search_div">
    	<div class="row">
            <div class="col-md-4">
            	<?=$this->form->pt_type?>
            </div>
            <div class="col-md-4">
            	<?=$this->form->keyword?>
            </div>
             <div class="col-md-4">
            	<?=$this->form->pl_added?>
            </div>
             <div class="clearfix"></div>
             <div class="col-md-12 text-center">
            	<?=$this->form->submitbtn?>
                <button type="button" name="export" class="btn blue btn-primary bttnsubmit hvr-inner-shadow  btn-default lead_mag btn btn-default" id="export">Export</button>
               
            </div>
        </div>
    </div>
      <input type="hidden" name="lp_id" id="lp_id" value="<?=@$this->search_array['lp_id']?>" />
    </form>
  </div>
  <br />
    <?php
                    	if(count($this->paginator)>0)
						{
							$i=1;
					?>
    <?php  foreach($this->paginator as $data)
							   {
								  // prn($data);
									?>
    <div class="col-md-12 text-left">
      <div class="col-md-12 lead_txt">
        <?=$data['pt_title']?>
        (
        <?php if($data['lp_name']!=''){ ?>
        <?=$data['lp_name']?>
        <?php } else {?>
         <?=$data['lp_url']?>
        <?php } ?>
        ) 
        </div>
      <div class="search_result_div">
        <div class="row">
          <div class="col-md-12"> <span class="name_title">Name </span> <span class="name_des">
            <?=$data['pl_name']?>
            </span> </div>
          <div class="col-md-12"> <span class="name_title">Email Address </span> <span class="name_des">
            <?=$data['pl_email']?>
            </span> </div>
          <?php if(($data['pt_id']!=4 && $data['pt_id']!=5 && $data['pt_id']!=6 && $data['pt_id']!=7) || ($data['pt_id']!=11) ){?>
          <?php if($data['pl_phone']!=''){?>
          <div class="col-md-12"> <span class="name_title">Phone Number </span> <span class="name_des">
            <?=$data['pl_phone']?>
            </span> </div>
            <?php }?>
          <?php }?>
          <?php if($data['pt_id']==3){?>
          <div class="col-md-12"> <span class="name_title">Number of bedrooms </span> <span class="name_des">
            <?=$data['pl_bedrooms']?>
            +</span> </div>
          <div class="col-md-12"> <span class="name_title">Number of bathrooms </span> <span class="name_des">
            <?=$data['pl_bathrooms']?>
            +</span> </div>
          <div class="col-md-12"> <span class="name_title">Price Range </span> <span class="name_des">
            <?=$data['pr_name']?>
            </span> </div>
              <div class="col-md-12"> <span class="name_title">Property Type </span> <span class="name_des">
            <?=$data['property_title']?>
            </span> </div>
          <div class="col-md-12"> <span class="name_title">Interest</span> <span class="name_des">
            <?=$data['pl_interest']?>
            </span> </div>
          <?php }?>
          <?php if($data['pt_id']==2 or $data['pt_id']==5 or $data['pt_id']==11){?>
          <div class="col-md-12"> <span class="name_title">Address </span> <span class="name_des">
            <?=$data['pl_address']?>
            </span> </div>
          <?php }?>
          <div class="col-md-12"> <span class="name_title">Date </span> <span class="name_des">
            <?=date("F j  Y",strtotime($data['pl_added']));?>
            </span> </div>
                    <a   onclick="check_dele('<?=$data['pl_id']?>')"class="dele_btn pull-right" >Delete</a>

        </div>
      </div>
    </div>
    <?php } 	
							echo $this->paginationControl($this->paginator,'Sliding','search-pagination-control.phtml'); 
							 echo "<br>";
							?>
    <?php } else { ?>
    <div class="col-md-12 overflow"> <br />
      <br />
    </div>
    <div class=" col-md-4 col-md-offset-4">
      <div class="noguard">
        <h3 class="text-center"><?php echo "No Result Found"; ?></h3>
      </div>
    </div>
    <div class="col-md-12 overflow"> <br />
      <br />
    </div>
    <?php } ?>
  </div>
</div>
<script>
function check_dele(pl_id)
{
	var c=false;
	c=confirm("Are you sure delete this record?");
	if(c)
	{
		window.location.href='<?=$this->baseUrl()?>/landingpages/removelead/pl_id/'+pl_id;	
	}
}
$('#export').click(function(e) {
    $('#search_form').attr('action','<?=$this->baseUrl()?>/landingpages/export');
	document.search_form.submit();
});
</script>