<div class="custom-form-wrapper">
   <div class="row">
      <div class="col-md-12 text-left  buyer_temp  text-center">Buyer Templates</div>
      <?php $i=0; foreach($this->buyer_temp as $k=>$v) {?>
      <div class="col-md-4 temp_padding">
         <div class="lead_div">
            <div class="marginbottom view_template_parent relativediv">
               <div class="thumbback" style="background-image:url('<?=HTTP_TEMPLATE_IMAGES?>/<?=$v['pt_thumb']?>')"></div>
               <!--<img class="" src="<?=HTTP_TEMPLATE_IMAGES?>/<?=$v['pt_thumb']?>"  alt="Lead" style="width:100%;" height="235"/>-->
               <div class="hover-text" ><?=$v['pt_des']?>
               </div>
            </div>
            <div class="col-md-12 lead_txt text-center">
               <?=$v['pt_title']?>
            </div>
            <?php /*?>
            <div class="col-md-12 text-justify oswaldfont">
               <?=$v['pt_des']?>
            </div>
            <?php */?>
            <p>
               <?php
                  $view_url='';
                  $view_url= get_redirect_url($v['pt_id']);
                  ?>
               <?php
                  if($i>0)
                  {
                  // echo "<br>";
                  }
                  ?>
               <!--                             <a class="view_template lineheight" target="_blank"  href="--><?php //echo $this->url(array(),$view_url)?><!--" >View Template</a>-->
               <?php if($v['pt_id']==5){ ?>
               <a class="custom_template"  href="<?=$this->baseUrl()?>/landingpages/addcustompage/pt_id/<?=$v['pt_id']?>" >Customize page</a>
               <?php } else if($v['pt_id']==6) {?>
               <a class="custom_template lineheight"  href="<?=$this->baseUrl()?>/landingpages/addnewbuyertemp/pt_id/<?=$v['pt_id']?>" >Customize page</a>
               <?php }
                  else {?>
               <a class="custom_template lineheight" href="<?php echo $this->url(array('pt_id'=>$v['pt_id']),'add_landing_page')?>"  >Customize page</a>
               <?php }?>
            </p>
         </div>
      </div>
      <?php $i++;} ?>
   </div>
   <div class="col-md-12"><br /></div>
   <div class="row">
      <div class="col-md-12 text-left  buyer_temp  text-center">Seller Templates</div>
      <?php $i=0; foreach($this->seller_temp as $k=>$v) {?>
      <div class="col-md-4 temp_padding">
         <div class="lead_div">
            <div class="marginbottom view_template_parent relativediv">
               <div class="thumbback" style="background-image:url('<?=HTTP_TEMPLATE_IMAGES?>/<?=$v['pt_thumb']?>')"></div>
               <!-- <img  class="" src="<?=HTTP_TEMPLATE_IMAGES?>/<?=$v['pt_thumb']?>"  alt="Lead" style="width:100%; " height="235"/>-->
               <div class="hover-text" ><?=$v['pt_des']?>
               </div>
            </div>
            <div class="col-md-12 lead_txt text-center ">
               <?=$v['pt_title']?>
            </div>
            <?php /*?>
            <div class="col-md-12 text-justify oswaldfont">
               <?=$v['pt_des']?>
            </div>
            <?php */?>
            <p>
               <?php
                  $view_url='';
                  $view_url= get_redirect_url($v['pt_id']);
                  ?>
               <?php
                  if($i>0)
                  {
                  // echo "<br>";
                  }
                  ?>
               <!--                             <a class=" view_template lineheight" target="_blank" href="--><?php //echo $this->url(array(),$view_url)?><!--">View Template</a>-->
               <?php if($v['pt_id']==5){ ?>
               <a class="custom_template lineheight"  href="<?=$this->baseUrl()?>/landingpages/addcustompage/pt_id/<?=$v['pt_id']?>" >Customize page</a>
               <?php } else if($v['pt_id']==6) {?>
               <a class="custom_template lineheight"  href="<?=$this->baseUrl()?>/landingpages/addnewbuyertemp/pt_id/<?=$v['pt_id']?>" >Customize page</a>
               <?php }
                  else {?>
               <a class="custom_template lineheight"  href="<?=$this->baseUrl()?>/landingpages/add/pt_id/<?=$v['pt_id']?>" >Customize page</a>
               <?php }?>
            </p>
         </div>
      </div>
      <?php $i++;} ?>
   </div>
   <!--New customize template--->
   <div class="clear-fix">&nbsp;</div>
   <div class="row">
      <div class="col-md-12 text-left  buyer_temp  text-center">CUSTOM TEMPLATES</div>
      <div class="col-md-4 temp_padding">
         <h5 class="buyer_temp">ALL NEW!</h5>
      </div>
   </div>
   <div class="clear-fix">&nbsp;</div>
      <div class="row">
  
   <?php 
      $i=0; foreach($this->custom_temp as $k=>$v) {?>
   <div class="col-md-4 temp_padding">
      <div class="lead_div">
         <div class="marginbottom view_template_parent relativediv">
            <div class="thumbback" style="background-image:url('<?=HTTP_TEMPLATE_IMAGES?>/<?=$v['pt_thumb']?>')"></div>
            <!--<img class="" src="<?=HTTP_TEMPLATE_IMAGES?>/<?=$v['pt_thumb']?>"  alt="Lead" style="width:100%;" height="235"/>-->
            <div class="hover-text" ><?=$v['pt_des']?>
            </div>
         </div>
         <div class="col-md-12 lead_txt text-center">
            <?=$v['pt_title']?>
         </div>
         <?php /*?>
         <div class="col-md-12 text-justify oswaldfont">
            <?=$v['pt_des']?>
         </div>
         <?php */?>
         <p>
            <?php
               $view_url='';
               $view_url= get_redirect_url($v['pt_id']);
               ?>
            <?php
               if($i>0)
               {
               // echo "<br>";
               }
               
               ?>
            <!--                             <a class="view_template lineheight" target="_blank"  href="--><?php //echo $this->url(array(),$view_url)?><!--" >View Template</a>-->
            <a class="custom_template lineheight" href="<?php echo $this->url(array('pt_id'=>$v['pt_id'],'lp_id'=>''),'add_custom_page')?>">Customize page</a>
         </p>
      </div>
   </div>
   <?php $i++;} ?>
</div>
      <!-- <div class="lead_div">
         <div class="marginbottom view_template_parent relativediv">
            <div class="thumbback" style="background-image:url('<?=HTTP_TEMPLATE_IMAGES?>/<?=$this->custom_temp['pt_thumb']?>')"></div>
            <div class="hover-text" ><?=$v['pt_des']?>
               </div>
         </div>
         <div class="col-md-12 lead_txt text-center ">
            CUSTOM LANDING PAGES 
         </div>
         <p>
            <a class=" view_template lineheight" target="_blank" href="/custom-templates">View Templates</a>
         </p>
      </div> -->
   </div>
</div>
<?php /*?>
<div class="col-md-12 custom_new">
   <div class="lead_div customize_option">
      <div class="inner_tab buyer_temp  text-center">
         New custom templates
      </div>
   </div>
   <a class=" view_template lineheight" target="_blank" href="/algdash/custom-templates">View Templates</a>          
</div>
<?php */?>
<div class="clear-fix">&nbsp;</div>
<script type="text/javascript">
   $(document).ready(function(){
      $(".view_template_parent").hover(function(){
          $(this).find(".hover-text").slideDown('fast,swing');
      },
      function(){
          $(this).find(".hover-text").slideUp('fast,swing');
      });
      $(".home-btn").hover(function(){
          $(this).find(".grey-area").show()
      },
      function() {
          $(this).find(".grey-area").hide()
      });
   
   }); 
   
</script>