<?php /*?><div class="homeval-step1 oswaldfont homeval-step2 text-center">
	<div class="row">
    	<div class="col-md-12">
        	<p class="head_style">AGAIN <?=$this->title?> HOME PRICES ARE ON THE RISE!</p>
        </div>
       	 <div class="col-md-10 col-md-offset-1 ">
        	<div class="row">
            	<div class="col-md-8"> <div id="pano"></div><div id="map"></div></div>
                <div class="col-md-4 form_field">
                	<p class="inner_txt">Your Property is Found!</p>
					<p><?=$this->form?></p>
                </div>
                
            </div>
        </div>
    </div>
</div><?php */?>




<?php
global $is_mobile;
?>
<?php if ($is_mobile==1){?>
<style>
#pano,#map
{
	height:480px;
	pointer-events: none !important;
}
.homeval-step2 .form_field {
    margin-top: 0px !important;
}
</style>

<?php } else {?>
<style>
#pano,#map
{
	height:480px !important;
}
.homeval-step2 .form_field {
    margin-top: 0px !important;
}
</style>

<?php } ?>
<div class="homeval-step1 homeval-step2 text-center">
	<div class="row">
    	<div class="col-md-12">
        	<p class="new_home_title">YOUR NEIGHBORS <?=$this->title?> HOME JUST SOLD!</p>
        </div>
        <div class="col-md-12">
        	<p class="sub_text">Find Out How This Affects Your Home's Current Value</p>
        </div>
        <div class="col-md-10 col-md-offset-1 new_margin">
        	<div class="row">
            	<div class="col-md-7"> <div id="pano"></div><div id="map"></div></div>
                <div class="col-md-5 form_field">
                	<p class="inner_txt full_text">Your Property is Found!</p>
                    <p class="cell_phone_class">Get Your Free Home Value Now- Absolutely No Obligation</p>
					<p><?=$this->form?></p>
                    <p class="cell_phone_class cell_phone_class1">
Want us to text you when your home valuation is ready?
<br />
<br />
<span>Enter your cell phone number below</span>
</p>
                </div>
                
            </div>
        </div>
    </div>
</div>

<script src="//maps.googleapis.com/maps/api/js?key=AIzaSyCV5Yqo_IxQXFyGLl0bEPJQuWBFKKG8fXA&v=3.exp&sensor=false"></script>
<script>
$(document).ready(function(e) {
	// $("#homeval_phone").mask("(999) 999-9999");
    $('<span class="fa fa-user fa_custom"></span>').insertAfter($('#homeval_name'));
	$('<span class="fa fa-phone fa_custom"></span>').insertAfter($('#homeval_phone'));
	$('.cell_phone_class1').insertAfter($('#pl_email').parent());
	
});

function initialize() {
  var fenway = {lat:<?=$_SESSION['homevalue']['homeval_Lat']?>, lng:<?=$_SESSION['homevalue']['homeval_Lng']?>};
   var map = new google.maps.Map(document.getElementById('map'), {
    center: fenway,
    zoom:15,
	center: fenway,
	zoom:15,
	scrollwheel: false,
	navigationControl: false,
	mapTypeControl: false,
	scaleControl: false,
	draggable: false,
  });
  var panorama = new google.maps.StreetViewPanorama(
      document.getElementById('pano'), {
        position: fenway,
		linksControl: false,
        panControl: false,
        enableCloseButton: false,
		 zoomControlOptions: false,
        pov: {
          heading: 34,
          pitch: 10
        }
      });
  map.setStreetView(panorama);
  
	var streetViewService = new google.maps.StreetViewService();
	var STREETVIEW_MAX_DISTANCE = 100;
	var latLng = new google.maps.LatLng(<?=$_SESSION['homevalue']['homeval_Lat']?>, <?=$_SESSION['homevalue']['homeval_Lng']?>);
	streetViewService.getPanoramaByLocation(latLng, STREETVIEW_MAX_DISTANCE, function (streetViewPanoramaData, status) {
	if (status === google.maps.StreetViewStatus.OK) {  
	$('#map').hide();
	geocodeAddress();
	} else { 
		$('#pano').hide();
			map = new google.maps.Map(document.getElementById('map'),map);
			marker = new google.maps.Marker({map: map});
			marker.setPosition(map.center);
	}
	});
}

$("#homeval_phone").on("blur", function() {
    var last = $(this).val().substr( $(this).val().indexOf("-") + 1 );
    
    if( last.length == 3 ) {
        var move = $(this).val().substr( $(this).val().indexOf("-") - 1, 1 );
        var lastfour = move + last;
        
        var first = $(this).val().substr( 0, 9 );
        
        $(this).val( first + '-' + lastfour );
    }
});


var geocoder = new google.maps.Geocoder();
var myStreetView = null;
var marker = null;
function geocodeAddress() { 

//console.log('<?=$_SESSION['homevalue']['homeval_address']?>');
   var address = "<?=$_SESSION['homevalue']['homeval_address']?>";
   // var address = document.getElementById('address').value;
    geocoder.geocode({
        'address': address
    }, function (results, status) {
        //alert (results);
        if (status == google.maps.GeocoderStatus.OK) {
            //alert(results[0].geometry.location);
            myStreetView = new google.maps.StreetViewPanorama(document.getElementById("pano"), {
       linksControl: false,
        panControl: false,
        enableCloseButton: false,
		 zoomControlOptions: false,
		 fullScreenControl: false,
       

      });
            myStreetView.setPosition(results[0].geometry.location);
            google.maps.event.addListenerOnce(myStreetView, 'status_changed', function () {
                var heading = google.maps.geometry.spherical.computeHeading(myStreetView.getLocation().latLng, results[0].geometry.location);
                myStreetView.setPov({
                    heading: heading,
                    pitch: 0,
					
                });
                setTimeout(function() {
                marker = new google.maps.Marker({
                    position: results[0].geometry.location,
                    map: myStreetView,
                    title: address
                });
                if (marker && marker.setMap) marker.setMap(myStreetView);}, 500);
            });

        } else {
            alert("Geocode was not successful for the following reason: " + status);
        }
    });
}
google.maps.event.addDomListener(window, 'load', initialize);
</script>

 