<?php echo $this->docType("HTML5");?>
<html lang="en">
<head>
<?php 
	echo $this->headMeta()."\n"; 
	echo $this->headTitle()."\n";
	echo $this->headLink()."\n";
	global $myActionName,$myControllerName,$myModuleName;
	$myControllerName=Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
	$myActionName=Zend_Controller_Front::getInstance()->getRequest()->getActionName();
	$myModuleName=Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
	//prd($myControllerName);
?>



<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="<?php echo $this->baseUrl()?>/public/front_js/html5shiv.js"></script>
  <script src="<?php echo $this->baseUrl()?>/public/front_js/respond.min.js"></script>
<![endif]-->
	
<script src="<?php echo $this->baseUrl('public/plugins/jquery-1.11.0.min.js')?>"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script>var baseUrl = SITEURL = SITE_URL = '<?php echo $this->baseUrl()?>';</script>
<script>
var controller='<?=$myControllerName?>';
var action='<?=$myActionName?>';
var module='<?=$myModuleName?>';

</script>	
<script>
$(window).load(function(e) {
	$('#wrap').hide();
});

</script>
</head>
<?
    global $bdy_class;
	if($myControllerName=='user' and $myActionName=='register') 
	{
		$bdy_class='choose_signup_class';
	}
	else if($myControllerName=='index' and $myActionName=='index') 
	{
		$bdy_class='index_class';
	}
	else if($myControllerName=='user' and $myActionName=='login') 
	{
		$bdy_class='choose_login_class';
	}
	else if($myControllerName=='user' and $myActionName=='forgotpassword') 
	{
		$bdy_class='choose_forgotpass_class';
	}
	else if($myControllerName=='user' and $myActionName=='resetpassword') 
	{
		$bdy_class='choose_resetpass_class';
	}
	else if($myControllerName=='profile' or $myControllerName=='error') 
	{
		$bdy_class='otherpages';
	}
	else if($myControllerName=='static') 
	{
		$bdy_class='otherpages layout_margin';
	}
	else
	{
		$bdy_class='';
	}
		
	?>
<body class="<?=$bdy_class?>">
	<div id="wrap" align="center">
	<img src="<?=HTTP_SITE_IMAGES?>/ajax-loader.gif" alt="loader"   id="logo-preloader" />
</div>
	<?php echo $this->render('header.phtml'); ?>
	<!--========================================== //End PROJECT-NAME Menu Section-->
	
    
	<?php echo $this->render("sub_home_slider.phtml");?>
    <?php if($myControllerName=='index' ||  ($myControllerName=='static' && $myActionName=='index')){?>
	<div class="fullwidthdiv">
    	<a href="<?php echo $this->url(array(),'contact_us')?>"  id="contact_right">Contact Us</a>
    </div>
    <?php } ?>
  	<div class="main-container-outer">
		<div class="main-layout-container ">
			
        <?
       	 if($myControllerName=='profile') {
		
		?>
        
        <div class="innerpage">
                        <div class="container" >
                            <div class="row"><?php echo $this->getHelper('Messages')->getMessages();?> </div>
                            <?php echo $this->render("sub_show_messages.phtml");?>
                        <br/>
                        	<div class="row row-offcanvas row-offcanvas-left">

								<?php if($this->user->user_id) { ?>
                                <div class="col-sm-3" id="sidebar" role="navigation" >
                                  <?php echo $this->render("_profile_side_bar.phtml");?>
                                </div>
                                <?php } ?>
                            
                                <div class="<?php if($this->user->user_id) { ?>col-sm-9<?php } else { ?>col-sm-12 <?php } ?>">
                                <?php echo $this->layout()->content?>
                            	</div>
                            
                            </div>
                            
                        </div>
                        <br/>
                    </div>
        
         <?php }else if($myControllerName=='static'){?>
					<?php echo $this->getHelper('Messages')->getMessages();?> 
 					<?php echo $this->render("sub_show_messages.phtml");?>
					<?php echo $this->layout()->content?>
        <?php }else{?>
        <?php if($myControllerName=='index' && $myActionName=='index'){ ?>
        
        
        
        <div  class="hidden-xs hidden-sm" id="video_main_parent">
          <div id="video_parent" style="position:absolute">
            <!--<video id="bgvid" preload="" autoplay loop onEnded="this.currentTime=0" height="100%" class="vjs-tech" src="https://player.vimeo.com/video/159360888">
              <object autoplay="" loop="" onended="this.currentTime=0" name="html5_video_fallback" style="width:100%;" class="leanback-player-flash-fallback" id="html5_video_fallback" width="100%" height="100%" type="application/x-shockwave-flash" data="http://praegnanz.de/html5video/player/leanback/player.swf">
                <param name="movie" value="http://praegnanz.de/html5video/player/leanback/player.swf">
                <param name="allowfullscreen" value="true">
                <param name="allowscriptaccess" value="always">
                <param name="wmode" value="transparent">
                <param name="aspectratio" value="16:9">
                <param name="flashvars" value="autostart=true&amp;controlbar=false&amp;controls=false&amp;file=https://player.vimeo.com/video/159360888">
              </object>
            </video>-->
          </div>
        </div>
        <?php } ?>
            <div class="container">
            
            
					<?php echo $this->getHelper('Messages')->getMessages();?> 
 					<?php echo $this->render("sub_show_messages.phtml");?>
					<?php echo $this->layout()->content?>
            </div>
        <?php } ?>    
         
		</div>
	</div>
	
 	
	<!--========================================== //End PROJECT-NAME Layout Section-->
	
	<?php //echo $this->render("sub_full_map.phtml");?>
	
	
	<?php //echo $this->render("sub_signup_social_buttons.phtml");?>
 	<?php if($bdy_class=='' or $bdy_class=='otherpages layout_margin' or $bdy_class=='otherpages'){?>
	<?php echo $this->render('footer.phtml');?>
    <?php }?>
	<!--========================================== //End PROJECT-NAME Footer Section-->
	
    
	<?php echo $this->headScript();?>
	
     
  </body>
</html>
