  <!-- Logo Section -->
            <section class="small-section pt-30 pt-xs-20 pb-30 pb-xs-20" style="background-color: #0069ff;">
                
                <div class="container align-center">
                    <div class="row">
                        <div class="col-xs-10 col-xs-offset-1">
                            <a href="#"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/logo.png" alt="" /></a>
                            <!-- Navigation panel -->
				            <nav class="main-nav mn-align-left not-top mt-20">
				                <div class="relative clearfix">
				                    
				                    <div class="mobile-nav">
				                        <i class="fa fa-bars"></i>
				                    </div>
				                    
				                    <!-- Main Menu -->
				                    <div class="inner-nav desktop-nav">
				                        <ul class="clearlist">
				                            <li>
				                                 <a href="<?php echo $this->baseUrl()?>/agent-lead"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/training-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">Training</div></a>
				                            </li>
				                            <li>
				                                 <a href="<?php echo $this->baseUrl()?>/agent-toolbox-lp"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/wrench-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">Agent Toolbox</div></a>  
				                            </li>
				                            
				                            <li>
				                                <a href="<?php echo $this->baseUrl()?>/profile/home"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/gear-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">ALG Dashboard</div></a>
				                            </li>
 				                        </ul>
				                    </div>
				                    <!-- End Main Menu -->
				                </div>
				            </nav>
				            <!-- End Navigation panel -->
				            <h1 style="margin-bottom: 0; font-weight: bold; color: white;">AGENT TOOLBOX</h1>
                        </div>
                    </div>
                </div>  
            </section>
            <!-- End Logo Section -->
            
            
            <!-- Landing Page Training Section-->
            <section class="page-section pt-30 pb-10">
                <div class="container relative">
                    <h2 class="section-title font-alt mb-70 mb-sm-40">
                        Click on any link to begin download
                    </h2>
                    <div class="row multi-columns-row">
                        
                        <!-- Training Item -->
                        <div class="col-sm-6 col-md-8 col-lg-8 col-md-offset-2 wow fadeIn" data-wow-delay="0.1s" data-wow-duration="2s">
                            
                        <h3 class="section-title-toolbox font-alt">Banner Ad Images</h3>

                        <p class="toolbox-content">
                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/files/Seller_Banners_Ads.zip" download>Seller Banner Ads</a>
                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/files/Buyer_Banners_Ads.zip" download>Buyer Banner Ads</a>
                        </p>

                        <h3 class="section-title-toolbox font-alt">Printable Pdf Guides</h3>

                        <p class="toolbox-content">
                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/files/Buyer_Leads_Homebuyer_Mistakes.pdf" download>Buyer Leads: Homebuyer Mistakes</a>

                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/files/Buyer_Leads_List_of_Homes.pdf" download>Buyer Leads: List of Homes</a>

                            <a>Buyer Leads: Current Active Listings</a>

                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/files/Seller_Leads_Home_Value.pdf" download>Seller Leads: Home Value</a>

                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/files/Seller_Leads_Sell_Your_Home_For_Top_Dollar.pdf" download>Seller Leads: Sell Your Home For Top Dollar</a>

                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/files/Seller_Leads_Custom_Home_Value.pdf" download>Seller Leads: Custom Home Value</a>

                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/files/Open_Houses.pdf" download>Open Houses</a>

                            <a  href="<?php echo PUBLIC_PATH?>/lead_www4/files/Direct-Mail-Marketing-Program.pdf"  download>Direct Mail Marketing</a>
                        </p>

                        <h3 class="section-title-toolbox font-alt">Printable Pdf Lead Magnets</h3>

                        <p class="toolbox-content">
                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/files/How-To-Sell-Your-Home-For-Top-Dollar.pdf" download>How To Sell Your Home For Top Dollar</a>

                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/files/Biggest-Homebuyer-Mistakes.pdf" download>Biggest Homebuyer Mistakes</a>
                        </p>

                        <h3 class="section-title-toolbox font-alt">Facebook Ad Images</h3>

                        <p class="toolbox-content">
                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/files/Homebuyer_Mistakes.jpg" download>Homebuyer Mistakes Landing Page</a>

                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/files/List_of_Homes.jpg" download>List of Homes Landing Page</a>

                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/files/Home_Value.jpg" download>Home Value Landing Page</a>

                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/files/Sell_Your_Home_For_Top_Dollar.jpg" download>Sell Your Home For Top Dollar Landing Page</a>

                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/files/Custom-Home-Value.jpg" download>Custom Home Value Landing Page
                            (Agent Provides The Image Of Their Listing In FB Ad)</a>
                        </p>

                        <h3 class="section-title-toolbox font-alt">Resources</h3>

                            <p class="toolbox-content">
                                <a href="<?php echo PUBLIC_PATH?>/lead_www4/files/Resources-for-Agent-Toolbox.docx" download>Click Here</a>
                            </p>
                        </div>
                        <!-- End Training Item -->
                         
                    </div>
                </div>
            </section>
            <!-- End Additional Training Section -->         
                      