<!-- Logo Section -->
            <section class="small-section pt-30 pt-xs-20 pb-30 pb-xs-20" style="background-color: #0069ff;">
                
                <div class="container align-center">
                    <div class="row">
                        <div class="col-xs-8 col-xs-offset-2">
                            <a href="#"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/logo.png" alt="" /></a>
                            <!-- Navigation panel -->
				            <nav class="main-nav mn-align-left not-top mt-20">
				                <div class="relative clearfix">
				                    
				                    <div class="mobile-nav">
				                        <i class="fa fa-bars"></i>
				                    </div>
				                    
				                    <!-- Main Menu -->
				                    <div class="inner-nav desktop-nav">
				                        <ul class="clearlist">
				                            <li>
				                                 <a href="<?php echo $this->baseUrl()?>/agent-lead"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/training-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">Training</div></a>
				                            </li>
				                            <li>
				                                 <a href="<?php echo $this->baseUrl()?>/agent-toolbox-lp"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/wrench-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">Agent Toolbox</div></a>  
				                            </li>
				                            
				                            <li>
				                                <a href="<?php echo $this->baseUrl()?>/profile/home"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/gear-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">ALG Dashboard</div></a>
				                            </li>
 				                        </ul>
				                    </div>
				                    <!-- End Main Menu -->
				                </div>
				            </nav>
				            <!-- End Navigation panel -->
				            <h1 style="margin-bottom: 0; font-weight: bold; color: white; text-transform: uppercase;">Guide To Open Houses</h1>
                        </div>
                    </div>
                </div>  
            </section>
            <!-- End Logo Section -->

            <section class="page-section pt-30 pb-30">
                <div class="container relative">
                    
                    <div class="row">
                        
                        <!-- Sidebar -->
                        <div class="col-sm-4 col-md-3 sidebar">
                        	
	                            <a href="https://drive.google.com/file/d/0B8Lu6Or0uwT6NjFxdnZ6ZmNlOVU/preview" class="html5lightbox" data-width="640" data-height="480" title="ALG Dash Tutorial"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/watch-the-video-btn.png" class="mb-30"></a>
	                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open_Houses.pdf" download><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/print-pdf-version-btn.png" class="mb-30"></a>
                           
                        </div>
                        <!-- End Sidebar -->

                        <!-- Content -->
                        <div class="col-sm-8">

                            <!-- Post Title -->
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <ul>
                                        <li>If you don’t already have a Facebook Community Business Page go to our step by step guide.</li>
                                        <li>If you don’t already have a Facebook personal page go to our step by step guide.</li>
                                        <li>Make sure you are using your “Community Business Page”. If you have a separate business page related directly to your Real Estate Company or brokerage DO NOT use that page.</li>
                                        <li>Use your Agent Lead Genesis dashboard to choose, create, and publish your landing page BEFORE you make your Facebook Ad.</li>
                                    </ul>

                                    <!-- STEP 1 -->
                                    <h2 class="section-title mb-10 mb-sm-40" style="letter-spacing: 0.3em;">
                                        STEP 1:  Login to your personal account at https://www.facebook.com/
                                    </h2>
                                    <p>
                                    	Click on the arrow on the top right top of your screen. Click on “CREATE ADS”.
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-1.png" class="center-block" />

                                    <!-- STEP 2 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 2:  Choose the objective for your campaign. 
                                    </h2>
                                    
                                    <p>
                                    	You will be sending people directly to your landing page to capture leads so you…   
                                    </p>

                                    <p>
                                        Click on “TRAFFIC” 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-2.png" class="center-block" />

                                    <!-- STEP 3 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 3
                                    </h2>
                                    <p>
                                    	Enter a Campaign Name in box. A Campaign Name will contain multiple ad sets and ads  within a campaign. Choose something like “Open House” and then your ad set within the campaign might be named “Open House Poppy Lane”.
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-3.png" class="center-block" />

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-4.png" class="center-block" />

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-5.png" class="center-block" />

                                    <p>
                                        Just keep this setting on default “Website or Messenger” 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-6.png" class="center-block" />

                                    <p>
                                        Also, keep this on default setting of “NO or OFF” 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-7.png" class="center-block" />

                                    <!-- STEP 4 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 4: LOCATION TARGETING 
                                    </h2>
                                    <p>
                                    	Choose the city you are marketing in with a radius. We have found that the majority of buyers will come from a larger area than sellers. Adjust the radius according to your surrounding area. If you live in a heavily and densely populated area your radius might only be 10miles. If your area is more rural and/or spread out you can take your radius up higher like 25 miles. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-8.png" class="center-block" />

                                    <!-- STEP 5 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 5: DEMOGRAPHIC TARGETING 
                                    </h2>
                                    <p>
                                    	Choose an age range of 25-65. Choose All Genders.Add “Likely to move” under behaviors for the “Detailed Targeting” field. Then, check the “SAVE THIS AUDIENCE” box. And, in the audience name put “Open House/Likely To Move” 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-9.png" class="center-block" />

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-10.png" class="center-block" />

                                    <p>
                                    	Click “Edit Placements”. Click on the arrow next to “Facebook” and UNCHECK “Right Column”. Also UNCHECK “Audience Network”.     
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-11.png" class="center-block" />

                                    <!-- STEP 6 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 6: BUDGETING
                                    </h2>
                                    <p>
                                    	Similar to other methods of advertising, Facebook ads is dependent on budget. The more money you spend, the larger your reach (the number of people your ad is shown to). For this ad you will run your ad for three or four days previous to your Open House. For example, if your Open House is on a Saturday from 1pm - 4pm you will run it from Thursday to Saturday at 4pm. If it’s on a Sunday from 1pm - 4pm you will run it from Thursday to Sunday at 4pm. We have found $5 to $10 a day for one week is sufficient. 
                                    </p>

                                    <p>
                                    	For “BUDGET” click Lifetime Budget” and enter $30 or $40 ($10 per day) depending on the number of days you are running ad.
                                    </p>

                                    <p>
                                    	For “SCHEDULE”, Facebook will default to “RUN MY AD CONTINUOUSLY STARTING TODAY”. Change that setting to “SET A START AND END DATE”.  
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-12.png" class="center-block" />

                                    <p>
                                        Click on the “START ” date box and enter whatever date you want your ad to begin. Click on the time box and enter “8:00 AM”. Click on the “END” date box and enter one week from your start date. Click on the time box and enter “8:00 PM”. Double check that you have entered “AM” to start and “PM” to end. You don’t want to waste precious ad time by mixing up the two. 
                                    </p>

                                    <!-- STEP 7 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 7: AD DELIVERY 
                                    </h2>

                                    <p>
                                    	Click Advanced Options and leave on default settings.
                                    </p>

                                    <p>
                                    	FFor “AD SET NAME” you can rename it to “Open House”. Click on the blue “Continue” button to move onto the next section. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-13.png" class="center-block" />

                                    <!-- STEP 8 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 8: AD IMAGES 
                                    </h2>

                                    <p>
                                    	Choose “Single Image” for the format.   
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-14.png" class="center-block" />

                                    <p>
                                    	Click on “UPLOAD IMAGES”. That will open up pictures you have stored on your computer
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-15.png" class="center-block" />

                                    <p>
                                    	For your Open House ad image you will choose a well lit, attractive front shot of your home you are featuring.  
                                    </p>

                                    <p>
                                    	The image that will be used in the ad will be framed by a red line. Make sure it is the correct image. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-16.png" class="center-block" />

                                    <!-- STEP 9 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 9: AD TEXT 
                                    </h2>

                                    <p>
                                    	Connect your “FACEBOOK BUSINESS PAGE” by clicking the arrow on the right. Your choices will drop down and you will choose the Page that you made SPECIFICALLY for your ads. Make sure you are NOT choosing your Facebook personal page or your Facebook business page that is associated with your name or company. If you have multiple Facebook Business Pages, make sure you are using the one that is congruent with the area of your listing.
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-17.png" class="center-block" />

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-18.png" class="center-block" />

                                    <p>
                                    	Leave the Instagram settings at the default. Facebook will automatically place your ad in the news feed of Instagram as well as Facebook. You DO NOT need to have an Instagram account to use this feature. There is no downside to using this feature. More reach always equals better results! 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-19.png" class="center-block" />

                                    <p>
                                    	In the Website URL field enter the EXACT URL of your listing or virtual tour. This is the website that ad visitors will go to when they click “Learn More” on your ad. Double check this URL is correct so visitors are sent to the right page with your listing details. You can send them to a single property website, a virtual tour, or your listing on the MLS.   
                                    </p>

                                    <p>
                                    	Leave Messenger options empty 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-20.png" class="center-block" />

                                    <p>
                                    	For the “HEADLINE” field enter the text “Stunning home in San Jose area!” Remember to change the term “San Jose” to the area you intend to target. Make sure it matches the area you used for the ad targeting and your List of Homes landing page. 
                                    </p>

                                    <p>
                                    	For the “TEXT” area enter the text “Beautiful San Jose Home For Sale!” Again, replace “San Jose with something from your area. Keep in mind the area you choose should match the area on the targeting of the ad as well as the List of Homes landing page. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-21.png" class="center-block" />

                                    <p>
                                        Keep the “CALL TO ACTION” button as “LEARN MORE”. 
                                    </p>

                                    <p>
                                    	Click on “SHOW ADVANCED OPTIONS” to show a drop down menu. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-22.png" class="center-block" />

                                    <p>
                                    	In the “NEWS FEED LINK DESCRIPTION” put enter the text “Huge lot in a desirable cul-de-sac location. Top rated schools and shopping nearby. Completely remodeled kitchen and bath.”Click “Learn More” for details.”
                                    </p>

                                    <p>
                                    	You can change out these details and pick two or three of your listings most desirable qualities. Remember, we want to grab people’s attention so pick details that are feature worthy and compelling to potential buyers.   
                                    </p>

                                    <p>
                                        For the display link FB asks that you put in the same URL as your Destination URL (this is where ad visitors are being sent when they click) You can copy and paste the URL from your property website, virtual tour, or MLS listing. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-23.png" class="center-block" />

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-24.png" class="center-block" />

                                    <p>
                                        Ignore the “URL Parameters” and “Pixel Tracking”. 
                                    </p>

                                    <p>
                                    	FB will add the image and text on the right side as you type to give you a you a preview of what your ad will look like. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-25.png" class="center-block" />

                                    <p>
                                    	Below your ad preview, click “REMOVE” next to “DESKTOP RIGHT COLUMN” and “AUDIENCE NETWORK”. The two that should be checked (look for a checkmark, NOT an X) are “MOBILE NEWS FEED” and “INSTAGRAM”.
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-26.png" class="center-block" />

                                    <p>
                                        Leave Pixel Tracking on the default setting (DO NOT track pixel conversion) 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-27.png" class="center-block" />

                                    <p>
                                        Click on Review order
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-28.png" class="center-block" />

                                    <p>
                                        Double check all the ad details and then click Place Order. Facebook will review your ad before placement. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/open_house_fb_ads/Open-Houses-29.png" class="center-block" />

                                </div>
                            </div>

                        </div>
                        <!-- End Content -->

                    </div>

                </div>

            </section>
            <!-- End Section -->