   <!-- Logo Section -->
            <section class="small-section pt-30 pt-xs-20 pb-30 pb-xs-20" style="background-color: #0069ff;">
                
                <div class="container align-center">
                    <div class="row">
                        <div class="col-xs-8 col-xs-offset-2">
                            <a href="#"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/logo.png" alt="" /></a>
                            <!-- Navigation panel -->
				            <nav class="main-nav mn-align-left not-top mt-20">
				                <div class="relative clearfix">
				                    
				                    <div class="mobile-nav">
				                        <i class="fa fa-bars"></i>
				                    </div>
				                    
				                    <!-- Main Menu -->
				                    <div class="inner-nav desktop-nav">
				                        <ul class="clearlist">
				                            <li>
				                                 <a href="<?php echo $this->baseUrl()?>/agent-lead"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/training-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">Training</div></a>
				                            </li>
				                            <li>
				                                 <a href="<?php echo $this->baseUrl()?>/agent-toolbox-lp"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/wrench-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">Agent Toolbox</div></a>  
				                            </li>
				                            
				                            <li>
				                                <a href="<?php echo $this->baseUrl()?>/profile/home"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/gear-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">ALG Dashboard</div></a>
				                            </li>
 				                        </ul>
				                    </div>
				                    <!-- End Main Menu -->
				                </div>
				            </nav>
				            <!-- End Navigation panel -->
				            <h1 style="margin-bottom: 0; font-weight: bold; color: white; text-transform: uppercase;">Guide to Buyer Leads: Current Active Listings Landing Page</h3>
                        </div>
                    </div>
                </div>  
            </section>
            <!-- End Logo Section -->

            <section class="page-section pt-30 pb-30">
                <div class="container relative">
                    
                    <div class="row">
                        
                        <!-- Sidebar -->
                        <div class="col-sm-4 col-md-3 sidebar">
                        	
	                            <a href="https://drive.google.com/file/d/0B8Lu6Or0uwT6eFFXTzVlOWRXZkU/preview" class="html5lightbox" data-width="640" data-height="480" title="ALG Dash Tutorial"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/watch-the-video-btn.png" class="mb-30"></a>
	                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Guide_To_Buyer_Leads_Current_Active_Listings_Landing_Page.pdf" download><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/print-pdf-version-btn.png" class="mb-30"></a>
                           
                        </div>
                        <!-- End Sidebar -->

                        <!-- Content -->
                        <div class="col-sm-8">

                            <!-- Post Title -->
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <ul>
                                        <li>If you don’t already have a Facebook Community Business Page go to our step by step guide.</li>
                                        <li>If you don’t already have a Facebook personal page go to our step by step guide.</li>
                                        <li>Make sure you are using your “Community Business Page”. If you have a separate business page related directly to your Real Estate Company or brokerage DO NOT use that page.</li>
                                        <li>Use your Agent Lead Genesis dashboard to choose, create, and publish your landing page BEFORE you make your Facebook Ad.</li>
                                    </ul>

                                    <!-- STEP 1 -->
                                    <h2 class="section-title mb-10 mb-sm-40" style="letter-spacing: 0.3em;">
                                        STEP 1:  Login to your personal account at https://www.facebook.com/
                                    </h2>
                                    <p>
                                    	Click on the arrow on the top right top of your screen. Click on “CREATE ADS”.
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-1.png" class="center-block" />

                                    <!-- STEP 2 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 2:  Choose the objective for your campaign. 
                                    </h2>
                                    <p>
                                    	These first few steps will change order depending on whether it is your first time creating a new ad account or you are returning. The instructions of choosing “TRAFFIC” for the Campaign Objective and naming the Campaign remain the same.   
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-2.png" class="center-block" />

                                    <!-- STEP 3 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 3
                                    </h2>
                                    <p>
                                    	Enter a Campaign Name in box. A Campaign Name will contain multiple ad sets and ads within a campaign. Choose something like “Current Active Listing” and then your ad set within the campaign might be named “Current Active Listing/San Jose/Sugar Pine/Lifetime $70”. From there you can name your ads with corresponding details to help you keep track of each ad. Make sure to replace “San Jose” with the city or area you are targeting.  
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-3.png" class="center-block" />

                                    <p>
                                    	The following screen shot will only appear the FIRST time you are creating an account. Click Continue 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-4.png" class="center-block" />

                                    <!-- STEP 4 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 4: LOCATION TARGETING 
                                    </h2>
                                    <p>
                                    	Keep the “TRAFFIC” setting on the default which is “Messenger or App” 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-5.png" class="center-block" />

                                    <p>
                                    	Keep  the “Offer” setting on default which “Off” 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-6.png" class="center-block" />

                                    <p>
                                    	Choose the city you are marketing in with a radius. We have found that the majority of buyers will come from a larger area than sellers. Adjust the radius according to your surrounding area. If you live in a heavily and densely populated area your radius might only be 10miles. If your area is more rural and/or spread out you can take your radius up higher   
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-7.png" class="center-block" />

                                    <!-- STEP 5 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 5: DEMOGRAPHIC TARGETING 
                                    </h2>
                                    <p>
                                    	In the audience name box put “Current Listing/San Jose/No Targeting”. Add the City or area name to the ad name. Click Save.
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-8.png" class="center-block" />

                                    <p>
                                    	Click “Edit Placements”. Click on the arrow next to “Facebook” and UNCHECK “Right Column” and “Instant Articles”. Also UNCHECK “Audience Network”. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-9.png" class="center-block" />

                                    <!-- STEP 6 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 6: BUDGET AND SCHEDULE 
                                    </h2>
                                    <p>
                                    	Similar to other methods of advertising, Facebook ads is dependent on budget. The more money you spend, the larger your reach (the number of people your ad is shown to). That being said, after lots of trial and error we have found $5 to $10 a day for one week is sufficient. . Remember, if things are going well, you can always add more money and extend the length of the Ad. Plan to review your results but give it time! 
                                    </p>

                                    <p>
                                    	For “BUDGET” click Lifetime Budget” and enter $70.00. 
                                    </p>

                                    <p>
                                    	For “SCHEDULE”, Facebook will default to “RUN MY AD CONTINUOUSLY STARTING TODAY”. Change that setting to “SET A START AND END DATE”.   
                                    </p>

                                    <p>
                                    	Click on the “START ” date box and enter whatever date you want your ad to begin. Click on the time box and enter “8:00 AM”. Click on the “END” date box and enter one month from your start date. Click on the time box and enter “8:00 PM”. Double check that you have entered “AM” to start and “PM” to end. You don’t want to waste precious ad time by mixing up the two.
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-10.png" class="center-block" />

                                    <!-- STEP 7 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 7: AD DELIVERY 
                                    </h2>

                                    <p>
                                    	Click Advanced Options and leave on default settings.
                                    </p>

                                    <p>
                                    	For “AD SET NAME” you can leave it as is or rename it to something more specific related to your ad like “Homebuyers/Charlotte/No Targeting/Lifetime $70”. The more details you provide here the easier it will be to keep track once you have multiple ad sets and ads. Click on the blue “Continue” button to move onto the next section.   
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-11.png" class="center-block" />

                                    <!-- STEP 8 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 8: AD IMAGES 
                                    </h2>

                                    <p>
                                    	Leave it as “A SINGLE VIDEO OR IMAGE IN YOUR ADS” 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-12.png" class="center-block" />

                                    <p>
                                    	Click on “UPLOAD IMAGES”. That will open up pictures you have stored on your computer.   
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-13.png" class="center-block" />

                                    <p>
                                    	For this ad you want to choose a beautiful picture of the front of your listing. If you don’t have a strong front of the home photo you can choose one from another area of the home. Make sure your photo is high quality and well lit. Remember the photo is the very first impression made with an ad visitor and potential lead. It needs to be strong!! 
                                    </p>

                                    <p>
                                    	Do not add more than one photo to the FB ad itself. There will be opportunities to add more photos on your landing page. If you need help with the “Current Active Listing” landing page please see our tutorial specifically for that page inside of your ALG Dashboard.   
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-14.png" class="center-block" />

                                    <p>
                                    	The image that will be used in the ad will be framed by a red line. Make sure it is the correct image
                                    </p>

                                    <!-- STEP 9 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 9: AD TEXT 
                                    </h2>

                                    <p>
                                    	Connect your “COMMUNITY FACEBOOK PAGE” by clicking the arrow on the right. Your choices will drop down and you will choose the Page that you made SPECIFICALLY for your ads. Make sure you are NOT choosing your Facebook personal page or your Facebook business page that is associated with your name or company. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-15.png" class="center-block" />

                                    <p>
                                    	Leave the Instagram settings at the default. Facebook will automatically place your ad in the news feed of Instagram as well as Facebook. You DO NOT need to have an Instagram account to use this feature. There is no downside to using this feature. More reach always equals better results!
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-16.png" class="center-block" />

                                    <p>
                                    	For the Website URL field it is very important that you input the correct URL. After all, this is where potential leads will go after they click on your ad! Remember, you will have already chosen, customized and published your List of Homs Landing page in your Agent Lead Genesis Dashboard at www.algdash.com. You will copy that same link and paste it in the Website URL field in Facebook. Facebook will test the URL to make sure it is functioning. Again, if you need any help creating the Current Active Listing landing page please see our tutorial.
                                    </p>

                                    <p>
                                    	Leave the “Messenger” choices uncheck 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-17.png" class="center-block" />

                                    <p>
                                    	For the “HEADLINE” field enter the text “Just listed: Stunning San Jose Home Now Available!” Remember to change the term “San Jose” to the area you intend to target. Make sure it matches the area you used for the ad targeting and your List of Homes landing page.  
                                    </p>

                                    <p>
                                    	Keep in mind this ad and landing page can be used for any current listing you have (or maybe another agent!). So you will use the specific text above only if it’s a brand new listing. If it’s not brand new you can remove the text “Just listed”,   
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-18.png" class="center-block" />

                                    <p>
                                    	For the “TEXT” area enter the text “Top Rated Schools in a Cul-De-Sac Location?” If you use a city or area in this text make sure it matches the area you are targeting with the FB ad as well as the landing page itself. This is the text that you really need to take into consideration your listing and it’s unique attributes. Pick a few features to showcase. Some examples might be “Top Rated Schools”, “Cul-De-Sac Location”, “Priced Below Comps”, “Move In Ready”, or “Central Location”. Pick features that make your listing attractive and unique. 
                                    </p>

                                    <p>
                                    	You will NOT include basics about the home such as bedrooms, bathrooms, and sq. ft. We want people to click on this ad and those details will be included on the next screen they visit which will be the landing page. 
                                    </p>

                                    <p>
                                    	Keep the “CALL TO ACTION” button as “LEARN MORE”. 
                                    </p>

                                    <p>
                                    	Click on “SHOW ADVANCED OPTIONS” to show a drop down menu. 
                                    </p>

                                    <p>
                                    	In the “NEWS FEED LINK DESCRIPTION” enter the text “Click below to learn more about this home.” 
                                    </p>

                                    <p>
                                    	Facebook requires the display link to be the same as the destination website URL (where visitors are sent after they click on ad) so just copy and paste the URL destination link from earlier in the process (ex. www.algdash.com/sanjose)  
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-19.png" class="center-block" />

                                    <p>
                                    	You’re almost there! 
                                    </p>

                                    <p>
                                    	As you create your ad text and image Facebook will update the right side to give you a preview of what your ad will look like.   
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-20.png" class="center-block" />

                                    <p>
                                    	Congratulations, you are now ready to place your Facebook Ad! 
                                    </p>

                                    <p>
                                    	Double check that everything is correct and click “PLACE ORDER”.Facebook will review your ad before it is approved. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/current_active_listings/Current-Active-Listings-21.png" class="center-block" />
                                 
                                </div>
                            </div>

                        </div>
                        <!-- End Content -->

                    </div>

                </div>

            </section>
            <!-- End Section -->
