 <!-- Logo Section -->
            <section class="small-section pt-30 pt-xs-20 pb-30 pb-xs-20" style="background-color: #0069ff;">
                
                <div class="container align-center">
                    <div class="row">
                        <div class="col-xs-8 col-xs-offset-2">
                            <a href="#"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/logo.png" alt="" /></a>
                            <!-- Navigation panel -->
				            <nav class="main-nav mn-align-left not-top mt-20">
				                <div class="relative clearfix">
				                    
				                    <div class="mobile-nav">
				                        <i class="fa fa-bars"></i>
				                    </div>
				                    
				                    <!-- Main Menu -->
				                    <div class="inner-nav desktop-nav">
				                        <ul class="clearlist">
				                            <li>
				                                 <a href="<?php echo $this->baseUrl()?>/agent-lead"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/training-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">Training</div></a>
				                            </li>
				                            <li>
				                                 <a href="<?php echo $this->baseUrl()?>/agent-toolbox-lp"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/wrench-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">Agent Toolbox</div></a>  
				                            </li>
				                            
				                            <li>
				                                <a href="<?php echo $this->baseUrl()?>/profile/home"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/gear-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">ALG Dashboard</div></a>
				                            </li>
 				                        </ul>
				                    </div>
				                    <!-- End Main Menu -->
				                </div>
				            </nav>
				            <!-- End Navigation panel -->
				            <h1 style="margin-bottom: 0; font-weight: bold; color: white; text-transform: uppercase;">GUIDE TO SELLER LEADS: HOME VALUE LANDING PAGE</h1>
                        </div>
                    </div>
                </div>  
            </section>
            <!-- End Logo Section -->

            <section class="page-section pt-30 pb-30">
                <div class="container relative">
                    
                    <div class="row">
                        
                        <!-- Sidebar -->
                        <div class="col-sm-4 col-md-3 sidebar">
                        	
	                            <a href="https://drive.google.com/file/d/0B0rrPaiRKJpWZVZoQ2tuNHJvRG8/preview" class="html5lightbox" data-width="640" data-height="480" title="ALG Dash Tutorial"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/watch-the-video-btn.png" class="mb-30"></a>
	                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller_Leads_Home_Value.pdf" download><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/print-pdf-version-btn.png" class="mb-30"></a>
	                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Home_Value.jpg" download><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/fb-ad-image-btn.png"></a>
                            
                        </div>
                        <!-- End Sidebar -->

                        <!-- Content -->
                        <div class="col-sm-8">

                            <!-- Post Title -->
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <ul>
                                        <li>If you don’t already have a Facebook Community Business Page go to our step by step guide.</li>
                                        <li>If you don’t already have a Facebook personal page go to our step by step guide.</li>
                                        <li>Make sure you are using your “Community Business Page”. If you have a separate business page related directly to your Real Estate Company or brokerage DO NOT use that page.</li>
                                        <li>Use your Agent Lead Genesis dashboard to choose, create, and publish your landing page BEFORE you make your Facebook Ad.</li>
                                    </ul>

                                    <!-- STEP 1 -->
                                    <h2 class="section-title mb-10 mb-sm-40" style="letter-spacing: 0.3em;">
                                        STEP 1:  Login to your personal account at https://www.facebook.com/
                                    </h2>
                                    <p>
                                    	Click on the arrow on the top right top of your screen. Click on “CREATE ADS”.
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-1.png" class="center-block" />

                                    <!-- STEP 2 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 2:  Choose the objective for your campaign. 
                                    </h2>
                                    
                                    <p>
                                    	You will be sending people directly to your landing page to capture leads so you…   
                                    </p>

                                    <p>
                                        Click on “TRAFFIC” 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-2.png" class="center-block" />

                                    <!-- STEP 3 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 3
                                    </h2>
                                    <p>
                                    	Enter a Campaign Name in box. A Campaign Name will contain multiple ad sets and ads  within a campaign. Choose something like “Home Value” and then your ad set within the campaign might be named “Home Value San Jose/No Radius/Lifetime $70”. From there you can name your ads with corresponding details to help you keep track of each ad. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-3.png" class="center-block" />

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-4.png" class="center-block" />

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-5.png" class="center-block" />

                                    <!-- STEP 4 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 4: LOCATION TARGETING 
                                    </h2>
                                    <p>
                                    	You can target a city,  several zip codes, a county, or a area such as Tri City Area. If you choose an area larger than a city (like a county or Tri City Area) try to pick the middle point on the map and add a radius to match your desired area. If you choose a single city, Facebook will automatically add a 25 mile radius. Make sure you remove the radius by clicking on the area next to the radius and choose “Current City Only”. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-6.png" class="center-block" />

                                    <!-- STEP 5 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 5: DEMOGRAPHIC TARGETING 
                                    </h2>
                                    <p>
                                    	Choose an age range of 23-65. Choose All Genders. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-7.png" class="center-block" />

                                    <p>
                                    	Skip the Detailed Targeting and Connections. Then, check the “SAVE THIS AUDIENCE” box.      
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-8.png" class="center-block" />

                                    <p>
                                        And, in the audience name put “Home Value/City/No Targeting”. Add the City or area name to the ad name. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-9.png" class="center-block" />

                                    <p>
                                        Click “Edit Placements”. Click on the arrow next to “Facebook” and UNCHECK “Right Column”. Also UNCHECK “Audience Network”.
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-10.png" class="center-block" />

                                    <!-- STEP 6 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 6: BUDGETING
                                    </h2>
                                    <p>
                                    	Similar to other methods of advertising, Facebook ads is dependent on budget. The more money you spend, the larger your reach (the number of people your ad is shown to). That being said, after lots of trial and error we have found $5 to $10 a day for one week is sufficient. Remember, if things are going well, you can always add more money and extend the length of the Ad, or if it’s doing poorly you can always turn off the ad. Plan to review your results but give it time! 
                                    </p>

                                    <p>
                                    	For “BUDGET” click Lifetime Budget” and enter $70.00. 
                                    </p>

                                    <p>
                                    	For “SCHEDULE”, Facebook will default to “RUN MY AD CONTINUOUSLY STARTING TODAY”. Change that setting to “SET A START AND END DATE”.   
                                    </p>

                                    <p>
                                    	Click on the “START ” date box and enter whatever date you want your ad to begin. Click on the time box and enter “8:00 AM”. Click on the “END” date box and enter one week from your start date. Click on the time box and enter “8:00 PM”. Double check that you have entered “AM” to start and “PM” to end. You don’t want to waste precious ad time by mixing up the two. Ignore the “Show Advanced Options” link below the “Budget &Schedule” fields. All of that info will be left on the default settings. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-11.png" class="center-block" />

                                    <!-- STEP 7 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 7: AD DELIVERY 
                                    </h2>

                                    <p>
                                    	Click Advanced Options and leave on default settings.
                                    </p>

                                    <p>
                                    	For “AD SET NAME” you can leave it as is or rename it to something more specific related to your ad like “Homebuyers/Charlotte/No Targeting/Lifetime $70”. The more details you provide here the easier it will be to keep track once you have multiple ad sets and ads. Click on the blue “Continue” button to move onto the next section.   
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-12.png" class="center-block" />

                                    <!-- STEP 8 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 8: AD IMAGES 
                                    </h2>

                                    <p>
                                    	Choose “Single Image” for the format.   
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-13.png" class="center-block" />

                                    <p>
                                    	Click on “UPLOAD IMAGES”. That will open up pictures you have stored on your computer.   
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-14.png" class="center-block" />

                                    <p>
                                    	We have a stock photo for you to use for your Home Value ads. We chose something that has nice color, is eye catching,  and stands out on the page. To access the photo, head login to your  ALG.com dashboard and click the black Education tab (If your not inside there already). Once inside the Education,  you can access the photo inside the "Seller Leads: Home Value" Training module .  Once inside the online "Home Value" Module, look on the left side of your screen and you will see the button labeled  FB AD IMAGE.  Alternatively, the photo is inside the "toolbox area" of your education system. It is the Home Value image and it is a bubble with a home inside. Download the image to your computer and upload when prompted on the ad.   
                                    </p>

                                    <p>
                                    	You are more than welcome to use the stock Home Value image. However, it would be ideal if you can choose a photo that represents the area you are marketing towards in your FB ad. Remember, particularly with photos, we want to illicit an emotional response from potential leads. When we include a photo that is quickly recognized  as something in their neighborhood or area it immediately becomes personal. Personal is important! Please remember Facebook tends to be very tricky when it comes to text inside of an ad image. So try to choose an image that has little or no text. Here are some examples you might use:
                                        
                                        <ul>
                                            <li>Arial shot of a sports stadium or area</li>
                                            <li>Downtown shot lit up at night </li>
                                            <li>A special statue or art piece that is well known to people in the area</li>
                                            <li>A historical building </li>
                                            <li>City Signs</li>
                                            <li>Any other structure or building that is recognizable</li>
                                        </ul>
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-15.png" class="center-block" />

                                    <p>
                                        The image that will be used in the ad will be framed by a red line. Make sure it is the correct image. 
                                    </p>

                                    <!-- STEP 9 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        STEP 9: AD TEXT 
                                    </h2>

                                    <p>
                                    	Connect your “FACEBOOK BUSINESS PAGE” by clicking the arrow on the right. Your choices will drop down and you will choose the Page that you made SPECIFICALLY for your ads. Make sure you are NOT choosing your Facebook personal page or your Facebook business page that is associated with your name or company. This is the Facebook Business Page that you made centered around the community you are targeting.
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-16.png" class="center-block" />

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-17.png" class="center-block" />

                                    <p>
                                    	Leave the Instagram settings at the default. Facebook will automatically place your ad in the news feed of Instagram as well as Facebook. You DO NOT need to have an Instagram account to use this feature. There is no downside to using this feature. More reach always equals better results! 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-18.png" class="center-block" />

                                    <p>
                                    	For the Website URL field it is very important that you input the correct URL. After all, this is
where potential leads will go after they click on your ad! Remember, you will have already
chosen, customized and published your Home Value Landing page in your Agent Lead Genesis
Dashboard at www.algdash.com. You will copy that same link and paste it in the Website URL
field in Facebook. Facebook will test the URL to make sure it is functioning.
                                    </p>

                                    <p>
                                    	Leave the “Messenger” choices uncheck 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-19.png" class="center-block" />

                                    <p>
                                    	For the “HEADLINE” field enter the text “Big Changes Are Happening In The San Jose Real
Estate Market!” Remember to change the term “San Jose” to the area you intend to target.
Make sure it matches the area you used for the ad targeting and your Home Value landing
page.
                                    </p>

                                    <p>
                                    	For the “TEXT” area enter the text “892 Homes Sold In San Jose Last Month” Again, replace
“San Jose” with something from your area. You can use a city, area (such as Tri City), or
county. Keep in mind the area you choose should match the area on the targeting of the ad as
well as the Home Valuelanding page.
                                    </p>

                                    <p>
                                    	Keep the “CALL TO ACTION” button as “LEARN MORE”. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-20.png" class="center-block" />

                                    <p>
                                    	Click on “SHOW ADVANCED OPTIONS” to show a drop down menu.
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-21.png" class="center-block" />

                                    <p>
                                    	In the “NEWS FEED LINK DESCRIPTION” put enter the text “Click below to find out your NEW home value.”. Again, make sure that area matches with other text in the ad as well as the targeting and landing page.  
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-22.png" class="center-block" />

                                    <p>
                                    	Facebook requires the display link to be the same as the destination website URL (where visitors are sent after they click on ad) so just copy and paste the URL destination link from earlier in the process (ex. www.algdash.com/sanjose) 
                                    </p>

                                    <p>
                                    	As you create your ad text and image Facebook will update the right side to give you a preview of what your ad will look like.   
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-23.png" class="center-block" />

                                    <p>
                                    	Below your ad preview, click “REMOVE” next to “DESKTOP RIGHT COLUMN” and “AUDIENCE NETWORK”. The two that should be checked (look for a checkmark, NOT an X) are “MOBILE NEWS FEED” and “INSTAGRAM”.   
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-24.png" class="center-block" />

                                    <p>
                                    	Double check the details of your ad and then click Place Order. Facebook will review your ad before placement. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-25.png" class="center-block" />


                                   	<h2 class="section-title mb-10 mb-sm-40 mt-30" style="letter-spacing: 0.3em;">
                                        You Have a Buyer Lead! Now What? Homebuyer Mistakes Follow Up  
                                    </h2>

                                    <p>
                                        This is the landing page that requires you, as the agent, to provide a CMA (Comparable Market Analysis) to the lead
                                    </p>

                                    <p>
                                    	You will need to take into account the amount of time and effort you would like to put into each of these CMA’s. You can also take into account the amount of contact you have had with the lead, if any. If you have more contact you will want to put forth more thought and analysis.   
                                    </p>

                                    <p>
                                    	If you have all information from the landing page (address, name, phone #) you will make contact with your lead and ideally set up an in home appointment to present your CMA. You will try to make contact with the lead via one of the following ways: 
                                    </p>

                                    <p>
                                    	<div class="col-sm-4 text-center">
                                    		<strong>- PHONE</strong>
                                    	</div>

                                    	<div class="col-sm-4 text-center">
                                    		<strong>- TEXT</strong>
                                    	</div>

                                    	<div class="col-sm-4 text-center">
                                    		<strong>- EMAIL</strong>
                                    	</div>
                                    </p>

                                    <p>
                                    	If you only have some of the information from the landing page you can try to gather some additional info using one of the following methods:  
                                    </p>

                                    <p>
                                        <ul>
                                            <li>www.whitepages.com (free, reverse ph. # and address lookup) </li>
                                            <li>www.intellius.com ($10 first month, then $20 per month, phone and email search) </li>
                                            <li>MLS (use address to search for owner of record)</li>
                                            <li>Google Search</li>
                                        </ul>
                                    </p>

                                    <p>
                                    	These systems above aren’t perfect; you may encounter outdated phone numbers or emails. But they are a great place to start!   
                                    </p>

                                    <p>
                                    	The nice thing about the Home Value landing page is that most everyone is going to put in the correct home address.  
                                    </p>

                                    <p>
                                    	If you don’t receive any response from your contact methods above you will still deliver the CMA. You can either mail it directly to their home or drop it off at their home. Remember to follow up even after the CMA is delivered.    
                                    </p>

                                    <p>
                                        If there is still no contact then you can add them to your CRM/Newsletter system and/or your direct mail campaign.   
                                    </p>

                                    <p class="mb-30">
                                    	** Remember that every lead is sent an automatic email on your behalf asking some sort of question in an attempt to start a conversation. Most leads will not respond but don’t be surprised if they do! Either way, you still need to move forward with the full process of following up with your leads. 
                                    </p>
                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/home_value/Seller-Leads-Home-Value-26.png" class="center-block" />

                                    <p class="mb-30">
                                    	A word about our lead philosophy
                                    </p>

                                    <p>
                                    	Try to treat every lead as incredibly valuable. Because it is! Try to respond as soon as possible and as personally as possible. You are the only one that knows your life, time commitments, and responsibilities. All of these will affect the amount of time and effort you will spend on each lead. It is really important to do YOUR best every time. Keep in mind you may get some fake names and phone numbers with these leads. It is normal and to be expected. Don’t get discouraged! Also remember that just because someone isn’t ready to sell or buy right now they may be ready 3 or 6 months down the road. You want them to remember that YOU provided something of value and followed up personally. Stick with it! 
                                    </p>
                                </div>
                            </div>

                        </div>
                        <!-- End Content -->

                    </div>

                </div>

            </section>
            <!-- End Section -->