
<div class="login"> 
  <!-- BEGIN LOGO -->
  <div class="logo"> 
</div>
  <!-- END LOGO --> 
  
  <!-- BEGIN LOGIN -->
  <div class="content">
    <div class="hr_main_div">
      <div class="hr_sub_div sub_div_1"></div>
      <div class="hr_sub_div sub_div_2"></div>
      <div class="hr_sub_div sub_div_3"></div>
      <div class="hr_sub_div sub_div_4"></div>
    </div>
    <div class="content_padding">
      <?=$this->form?>
    </div>
    <div class="hr_main_div text-center bottom_info_div"> <span><a  class="signu_txt" href="<?=$this->baseUrl()?>/register">Sign Up Now !</a></span> <span class="btw_span"> | </span> <span><a  class="for_got_txt" href="<?=$this->baseUrl()?>/forgot-password">Forgot your password?</a></span> </div>
  </div>
  <!-- END LOGIN --> 
  
</div>
