  <!-- Logo Section -->
            <section class="small-section pt-30 pt-xs-20 pb-30 pb-xs-20" style="background-color: #0069ff;">
                
                <div class="container align-center">
                    <div class="row">
                        <div class="col-xs-10 col-xs-offset-1">
                            <a href="#">
                            </a>
                            <!-- Navigation panel -->
				            <nav class="main-nav mn-align-left not-top mt-20">
				                <div class="relative clearfix">
				                    
				                    <div class="mobile-nav">
				                        <i class="fa fa-bars"></i>
				                    </div>
				                    
				                    <!-- Main Menu -->
				                    <div class="inner-nav desktop-nav">
				                        <ul class="clearlist">
				                            <li>
				                                 <a href="#"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/training-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">Training</div></a>
				                            </li>
				                            <li>
				                                 <a href="<?php echo $this->baseUrl()?>/agent-toolbox-lp"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/wrench-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">Agent Toolbox</div></a>  
				                            </li>
				                            
				                            <li>
				                                <a href="<?php echo $this->baseUrl()?>/profile/home"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/gear-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">ALP Dashboard</div></a>
				                            </li>
 				                        </ul>
				                    </div>
				                    <!-- End Main Menu -->
				                </div>
				            </nav>
				            <!-- End Navigation panel -->
				            <h1 style="margin-bottom: 0; font-weight: bold; color: white;">TRAINING</h1>
                        </div>
                    </div>
                </div>  
            </section>
            <!-- End Logo Section -->
            
            
            <!-- Landing Page Training Section-->
            <section class="page-section pt-30 pb-10">
                <div class="container relative">
                    <h2 class="section-title font-alt mb-70 mb-sm-40">
                        Landing Page Training-Facebook Ads
                    </h2>
                    <div class="row multi-columns-row">
                        
                        <!-- Training Item -->
                        <div class="col-sm-6 col-md-4 col-lg-4 mb-md-50 wow fadeIn" data-wow-delay="0.1s" data-wow-duration="2s">
                            
                            <div class="post-prev-img">
                                <a href="<?php echo $this->baseUrl()?>/homebuyer-mistakes"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/homebuyer-mistakes.jpg" alt="" /></a>
                            </div>
                            
                            <div class="post-prev-title font-alt">
                                <a href="<?php echo $this->baseUrl()?>/homebuyer-mistakes">BUYER LEADS: HOMEBUYER MISTAKES</a>
                            </div>

                        </div>
                        <!-- End Training Item -->
                        
                        <!-- Training Item -->
                        <div class="col-sm-6 col-md-4 col-lg-4 mb-md-50 wow fadeIn" data-wow-delay="0.2s" data-wow-duration="2s">
                            
                            <div class="post-prev-img">
                                <a href="<?php echo $this->baseUrl()?>/list-of-homes"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/list-of-homes.jpg" alt="" /></a>
                            </div>
                            
                            <div class="post-prev-title font-alt">
                                <a href="<?php echo $this->baseUrl()?>/list-of-homes">BUYER LEADS: LIST OF HOMES</a>
                            </div>
                            
                        </div>
                        <!-- End Training Item -->
                        
                        <!-- Training Item -->
                        <div class="col-sm-6 col-md-4 col-lg-4 mb-md-50 wow fadeIn" data-wow-delay="0.3s" data-wow-duration="2s">
                            
                            <div class="post-prev-img">
                                <a  href="<?php echo $this->baseUrl()?>/current-active-listings"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/current-active-listings.jpg" alt="" /></a>
                            </div>
                            
                            <div class="post-prev-title font-alt">
                                <a href="<?php echo $this->baseUrl()?>/current-active-listings">BUYER LEADS: CURRENT ACTIVE LISTINGS</a>
                            </div>
                            
                        </div>
                        <!-- End Training Item -->
                        
                    </div>

                    <div class="row multi-columns-row mt-30">
                        
                        <!-- Training Item -->
                        <div class="col-sm-6 col-md-4 col-lg-4 mb-md-50 wow fadeIn" data-wow-delay="0.1s" data-wow-duration="2s">
                            
                            <div class="post-prev-img">
                                <a href="<?php echo $this->baseUrl()?>/home-value"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/home-value.jpg" alt="" /></a>
                       </div>
                            
                            <div class="post-prev-title font-alt">
                                <a href="<?php echo $this->baseUrl()?>/home-value">SELLER LEADS: HOME VALUE</a>
                            </div>

                        </div>
                        <!-- End Training Item -->
                        
                        <!-- Training Item -->
                        <div class="col-sm-6 col-md-4 col-lg-4 mb-md-50 wow fadeIn" data-wow-delay="0.2s" data-wow-duration="2s">
                            
                            <div class="post-prev-img">
                                <a href="<?php echo $this->baseUrl()?>/sell-your-home-for-top-dollar"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/sell-your-home-for-more.jpg" alt="" /></a>
                            </div>
                            
                            <div class="post-prev-title font-alt">
                                <a href="<?php echo $this->baseUrl()?>/sell-your-home-for-top-dollar">SELLER LEADS: SELL YOUR HOME FOR MORE</a>
                            </div>
                            
                        </div>
                        <!-- End Training Item -->
                        
                        <!-- Training Item -->
                        <div class="col-sm-6 col-md-4 col-lg-4 mb-md-50 wow fadeIn" data-wow-delay="0.3s" data-wow-duration="2s">
                            
                            <div class="post-prev-img">
                                <a href="<?php echo $this->baseUrl()?>/custom-home-value"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/dont-leave-money-on-the-table.jpg" alt="" /></a>
                            </div>
                            
                            <div class="post-prev-title font-alt">
                                <a href="<?php echo $this->baseUrl()?>/custom-home-value">SELLER LEADS: CUSTOM HOME VALUE</a>
                            </div>
                            
                        </div>
                        <!-- End Training Item -->
                        
                    </div>
                    
                </div>
            </section>
            <!-- End Landing Page Training Section -->

            <!-- Additional Training Section-->
            <section class="page-section pt-20 pb-0">
                <div class="container relative">
                    <h2 class="section-title font-alt mb-70 mb-sm-40">
                        Additional Training
                    </h2>
                    <div class="row multi-columns-row">
                        
                        <!-- Additional Training Item -->
                        <div class="col-sm-6 col-md-4 col-lg-4 mb-md-50 wow fadeIn" data-wow-delay="0.1s" data-wow-duration="2s">
                            
                            <div class="post-prev-img">
                                <a href="<?php echo $this->baseUrl()?>/at-1-open-house"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/fb-ad.jpg" alt="" /></a>
                            </div>
                            
                            <div class="post-prev-title font-alt">
                                <a href="<?php echo $this->baseUrl()?>/at-1-open-house">OPEN HOUSE FB AD</a>
                            </div>

                        </div>
                        <!-- End Additional Training Item -->
                        
                        <!-- Additional Training Item -->
                        <div class="col-sm-6 col-md-4 col-lg-4 mb-md-50 wow fadeIn" data-wow-delay="0.2s" data-wow-duration="2s">
                            
                            <div class="post-prev-img">
                                <a href="<?php echo $this->baseUrl()?>/at-2-banner-ads-tutorial"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/banner-ad.jpg" alt="" /></a>
                            </div>
                            
                            <div class="post-prev-title font-alt">
                                <a href="<?php echo $this->baseUrl()?>/at-2-banner-ads-tutorial">BANNER ADS</a>
                            </div>
                            
                        </div>
                        <!-- End Additional Training Item -->
                        
                        <!-- Additional Training Item -->
                        <div class="col-sm-6 col-md-4 col-lg-4 mb-md-50 wow fadeIn" data-wow-delay="0.3s" data-wow-duration="2s">
                            
                            <div class="post-prev-img">
                                <a href="<?php echo $this->baseUrl()?>/direct-mail"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/direct-mail.jpg" alt="" /></a>
                            </div>
                            
                            <div class="post-prev-title font-alt">
                                <a  href="<?php echo $this->baseUrl()?>/direct-mail">DIRECT MAIL (EVERY DOOR DIRECT)</a>
                            </div>
                            
                        </div>
                        <!-- End Additional Training Item -->
                        
                    </div>
                    
                </div>
            </section>
            <!-- End Additional Training Section -->

            <!-- Tutorial Video Section-->
            <section class="page-section pb-0 pt-20">
                <div class="container relative">
                    <h2 class="section-title font-alt mb-70 mb-sm-40">
                        Video Tutorial
                    </h2>
                    
                    <div class="row multi-columns-row">
                        
                        <!-- Video Tutorial Item -->
                        <div class="col-sm-6 col-md-4 col-lg-4 mb-md-50 wow fadeIn" data-wow-delay="0.1s" data-wow-duration="2s">
                            
                            <div class="post-prev-img">
                                <a href="https://drive.google.com/file/d/0B8Lu6Or0uwT6N0NtWVl4SDhNeGc/preview" class="html5lightbox" data-width="640" data-height="480" title="Start Here"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/training-1.jpg" alt="" /></a>
                            </div>
                            
                            <div class="post-prev-title font-alt">
                                <a href="https://drive.google.com/file/d/0B8Lu6Or0uwT6N0NtWVl4SDhNeGc/preview" class="html5lightbox" data-width="640" data-height="480" title="Start Here">Start Here</a>
                            </div>

                        </div>
                        <!-- End Video Tutorial Item -->
                        
                        <!-- Video Tutorial Item -->
                        <div class="col-sm-6 col-md-4 col-lg-4 mb-md-50 wow fadeIn" data-wow-delay="0.1s" data-wow-duration="2s">
                            
                            <div class="post-prev-img">
                                <a href="https://drive.google.com/file/d/0B8Lu6Or0uwT6MWxSZlBvSFpfd00/preview" class="html5lightbox" data-width="640" data-height="480" title="How To Make a FB Personal Page"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/training-2.jpg" alt="" /></a>
                            </div>
                            
                            <div class="post-prev-title font-alt">
                                <a href="https://drive.google.com/file/d/0B8Lu6Or0uwT6MWxSZlBvSFpfd00/preview" class="html5lightbox" data-width="640" data-height="480" title="How To Make a FB Personal Page">How To Make a FB Personal Page</a>
                            </div>

                        </div>
                        <!-- End Video Tutorial Item -->
                        
                        <!-- Video Tutorial Item -->
                        <div class="col-sm-6 col-md-4 col-lg-4 mb-md-50 wow fadeIn" data-wow-delay="0.1s" data-wow-duration="2s">
                            
                            <div class="post-prev-img">
                                <a href="https://drive.google.com/file/d/0B-5xMbr2LgGfcGhrMkRfVW5EODg/preview" class="html5lightbox" data-width="640" data-height="480" title="How To Make a FB COMMUNITY Business Page"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/training-3.jpg" alt="" /></a>
                            </div>
                            
                            <div class="post-prev-title font-alt">
                                <a href="https://drive.google.com/file/d/0B-5xMbr2LgGfcGhrMkRfVW5EODg/preview" class="html5lightbox" data-width="640" data-height="480" title="How To Make a FB COMMUNITY Business Page">How To Make a FB COMMUNITY Business Page</a>
                            </div>

                        </div>
                        <!-- End Video Tutorial Item -->

                        <!-- Video Tutorial Item -->
                        <div class="col-sm-6 col-md-4 col-lg-4 mb-md-50 wow fadeIn" data-wow-delay="0.1s" data-wow-duration="2s">
                            
                            <div class="post-prev-img">
                                <a href="https://drive.google.com/file/d/0B8Lu6Or0uwT6bFJjOUlhNUxrT2M/preview" class="html5lightbox" data-width="640" data-height="480" title="ALP Dash Tutorial"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/training-4.jpg" alt="" /></a>
                            </div>
                            
                            <div class="post-prev-title font-alt">
                                <a href="https://drive.google.com/file/d/0B8Lu6Or0uwT6bFJjOUlhNUxrT2M/preview" class="html5lightbox" data-width="640" data-height="480" title="ALP Dash Tutorial">ALP Dash Tutorial</a>
                            </div>

                        </div>
                        <!-- End Video Tutorial Item -->

                        <!-- Video Tutorial Item -->
                        <div class="col-sm-6 col-md-4 col-lg-4 mb-md-50 wow fadeIn" data-wow-delay="0.1s" data-wow-duration="2s">
                            
                            <div class="post-prev-img">
                                <a href="https://drive.google.com/file/d/0B8Lu6Or0uwT6aDd1dlRtQXVjU2M/preview" class="html5lightbox" data-width="640" data-height="480" title="How To Create A landing Page"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/training-5.jpg" alt="" /></a>
                            </div>
                            
                            <div class="post-prev-title font-alt">
                                <a href="https://drive.google.com/file/d/0B8Lu6Or0uwT6aDd1dlRtQXVjU2M/preview" class="html5lightbox" data-width="640" data-height="480" title="How To Create A landing Page">How To Create A landing Page</a>
                            </div>

                        </div>
                        <!-- End Video Tutorial Item -->
                        
                    </div>
                </div>
            </section>
            <!-- End Additional Training Section -->         
                      
            <!-- Foter -->