 <!-- Logo Section -->
            <section class="small-section pt-30 pt-xs-20 pb-30 pb-xs-20 header-bg-color">
                
                <div class="container align-center">
                    <div class="row">
                        <div class="col-xs-8 col-xs-offset-2">
                            <a href="#">
                            </a>
                            <!-- Navigation panel -->
				            <nav class="main-nav mn-align-left not-top mt-20">
				                <div class="relative clearfix">
				                    
				                    <div class="mobile-nav">
				                        <i class="fa fa-bars"></i>
				                    </div>
				                    
				                    <!-- Main Menu -->
				                    <div class="inner-nav desktop-nav">
				                        <ul class="clearlist">
				                            <li>
				                                 <a href="<?php echo $this->baseUrl()?>/agent-lead"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/training-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">Training</div></a>
				                            </li>
				                            <li>
				                                 <a href="<?php echo $this->baseUrl()?>/agent-toolbox-lp"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/wrench-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">Agent Toolbox</div></a>  
				                            </li>
				                            
				                            <li>
				                                <a href="<?php echo $this->baseUrl()?>/profile/home"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/gear-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">ALP Dashboard</div></a>
				                            </li>
 				                        </ul>
				                    </div>
				                    <!-- End Main Menu -->
				                </div>
				            </nav>
				            <!-- End Navigation panel -->
				            <h1 class="main-heading">Guide To Banner Ads</h1>
                        </div>
                    </div>
                </div>  
            </section>
            <!-- End Logo Section -->

            <section class="page-section pt-30 pb-30">
                <div class="container relative">
                    
                    <div class="row">
                        
                        <!-- Sidebar -->
                       <!--  <div class="col-sm-4 col-md-3 sidebar">
                        	
	                            <a href="https://drive.google.com/file/d/0B8Lu6Or0uwT6aVh3MV85YW95cE0/preview" class="html5lightbox" data-width="640" data-height="480" title="ALG Dash Tutorial"><img src="<?php //echo PUBLIC_PATH?>/lead_www4/images/lead/watch-the-video-btn.png" class="mb-30"></a>
                                <a href="<?php //echo PUBLIC_PATH?>/lead_www4/images/banner_images/bannerads.zip" download><img src="<?php //echo PUBLIC_PATH?>/lead_www4/images/lead/banner-image-btn.png"></a>
                           
                        </div> -->
                        <!-- End Sidebar -->

                        <!-- Content -->
                        <div class="col-sm-12 col-md-12">

                            <!-- Post Title -->
                            <div class="video-shadow">
                                <div class="embed-responsive embed-responsive-16by9">
                                    <iframe style="margin:0;padding:0;border:0;" id="html5lightbox-web-iframe" width="100%" height="100%" src="https://drive.google.com/file/d/0B8Lu6Or0uwT6aVh3MV85YW95cE0/preview" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen=""></iframe>
                                </div>
                            </div>  
                            <div class="row">
                                <div class="mg-btm">
                                     <div class="col-md-6">
                                         <div class="banner-img-btn">
                                              <a href="<?php echo PUBLIC_PATH?>/lead_www4/images/banner_images/bannerads.zip" download><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/banner-image.png"><span>Banner Image</span></a>
                                         </div>
                                     </div>
                                     <div class="col-md-6">
                                         <div class="fb-btn fl-left">
                                             <!-- <a href=" https://drive.google.com/file/d/0B8Lu6Or0uwT6Z2FGLXdkOUtSLXM/preview" class="html5lightbox" data-width="640" data-height="480" title="ALG Dash Tutorial"> --><a href="#"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/Fb-post.png" ><span>Example FB Post</span> </a><!-- </a> -->
                                         </div>
                                     </div>
                                 </div>
                             </div>     

                        </div>
                        <!-- End Content -->

                    </div>

                </div>

            </section>
            <!-- End Section -->