 <!-- Logo Section -->
            <section class="small-section pt-30 pt-xs-20 pb-30 pb-xs-20 header-bg-color">
                
                <div class="container align-center">
                    <div class="row">
                        <div class="col-xs-8 col-xs-offset-2">
                            <a href="#">
                        </a>
                            <!-- Navigation panel -->
				            <nav class="main-nav mn-align-left not-top mt-20">
				                <div class="relative clearfix">
				                    
				                    <div class="mobile-nav">
				                        <i class="fa fa-bars"></i>
				                    </div>
				                    
				                    <!-- Main Menu -->
				                    <div class="inner-nav desktop-nav">
				                        <ul class="clearlist">
				                            <li>
				                                 <a href="<?php echo $this->baseUrl()?>/agent-lead"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/training-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">Training</div></a>
				                            </li>
				                            <li>
				                                 <a href="<?php echo $this->baseUrl()?>/agent-toolbox-lp"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/wrench-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">Agent Toolbox</div></a>  
				                            </li>
				                            
				                            <li>
				                                <a href="<?php echo $this->baseUrl()?>/profile/home"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/gear-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">ALG Dashboard</div></a>
				                            </li>
 				                        </ul>
				                    </div>
				                    <!-- End Main Menu -->
				                </div>
				            </nav>
				            <!-- End Navigation panel -->
				            <h1 class="main-heading">Buyer Guide to Facebook Ads: Homebuyer Mistakes Landing Page</h1>
                        </div>
                    </div>
                </div>  
            </section>
<!-- End Logo Section -->

            <section class="page-section pt-30 pb-30">
                <div class="container relative">       
                    <div class="row">
                        
                        <!-- Sidebar -->
                       <!--  <div class="col-sm-4 col-md-3 sidebar">
                        	
	                            
	                            <a href="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer_Leads_Homebuyer_Mistakes.pdf" download><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/print-pdf-version-btn.png" class="mb-30"></a>
	                            
                           
                        </div> -->
                        <!-- End Sidebar -->

                        <!-- Content -->
                        <div class="col-sm-12 col-md-12">

                            <!-- Post Title -->
                            <!-- <div class="panel panel-default"> -->
                                <div class="step1-section">
                                    <h2 class="section-title mb-10 mb-sm-40">
                                        <strong>STEP 1:</strong> Login to your personal account at https://www.facebook.com
                                    </h2>
                                 <div class="video-shadow">
                                     <div class="embed-responsive embed-responsive-16by9">
										<iframe style="margin:0;padding:0;border:0;" id="html5lightbox-web-iframe" width="100%" height="100%" src="https://drive.google.com/file/d/0B8Lu6Or0uwT6Z2FGLXdkOUtSLXM/preview" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen=""></iframe>                                    </div>
                                 </div>   
                                  
                             </div>
                                
                                <div class="row">
                                    <div class="down-content">
                                        <div class="col-md-8">
                                            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                                                    <div class="panel panel-default bd-color">
                                                        <div class="panel-heading bg-color" role="tab" id="headingOne">
                                                          <h4 class="panel-title">
                                                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                                              Login to your personal account
                                                              <span><i class="fa fa-angle-down" aria-hidden="true"></i></span>
                                                            </a>
                                                          </h4>
                                                        </div>
                                                        <div id="collapseOne" class="panel-collapse collapse " role="tabpanel" aria-labelledby="headingOne">
                                                          <div class="panel-body">
                                                           <ul>
                                                                <li>If you don’t already have a Facebook Community Business Page go to our step by step guide.</li>
                                                                <li>If you don’t already have a Facebook personal page go to our step by step guide.</li>
                                                                <li>Make sure you are using your “Community Business Page”. If you have a separate business page related directly to your Real Estate Company or brokerage DO NOT use that page.</li>
                                                                <!-- <li>Use your Agent Lead Genesis dashboard to choose, create, and publish your landing page BEFORE you make your Facebook Ad.</li> -->
                                                                <li>Use your dashboard to choose, create, and publish your landing page BEFORE you make your Facebook Ad.</li>
                                                            </ul>

                                                    <!-- STEP 1 -->
                                                                <p>Click on the arrow on the top right top of your screen. Click on “CREATE ADS”.</p>
                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-1.png" class="center-block" />
                                                                <!-- STEP 2 -->
                                                                <h2 class="section-title  mb-sm-40 mt-30" >
                                                                    <strong>STEP 2:</strong> Choose the objective for your campaign. 
                                                                </h2>
                                                                <p>
                                                                    These first few steps will change order depending on whether it is your first time creating a new ad account or you are returning. The instructions of choosing “TRAFFIC” for the Campaign Objective and naming the Campaign remain the same.   
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-2.png" class="center-block" />

                                                                <p>
                                                                    You will be sending people directly to your landing page to capture leads so you… 
                                                                </p> 
                                                                <p>
                                                                    Click on “SEND PEOPLE TO YOUR WEBSITE
                                                                </p>

                                                                <!-- STEP 3 -->
                                                                <h2 class="section-title mb-sm-40 mt-30" >
                                                                    <strong>STEP 3:</strong>
                                                                </h2>
                                                                <p>
                                                                    Enter a Campaign Name in box. A Campaign Name will contain multiple ad sets and ads  within a campaign. Choose something like “Homebuyer Mistakes” and then your ad set within the campaign might be named “Homebuyer Mistakes Charlotte/10 mile Radius/Lifetime/ $70”. From there you can name your ads with corresponding details to help you keep track of each ad. Make sure to replace “Charlotte” with the city or area you are targeting. 
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-3.png" class="center-block" />

                                                                <p>
                                                                    The following screen shot will only appear the FIRST time you are creating an account. Click Continue 
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-4.png" class="center-block" />

                                                                <!-- STEP 4 -->
                                                                <h2 class="section-title mb-sm-40 mt-30" >
                                                                    <strong>STEP 4:</strong> LOCATION TARGETING 
                                                                </h2>
                                                                <p>
                                                                    Keep the “TRAFFIC” setting on the default which is “Messenger or App” 
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-5.png" class="center-block" />

                                                                <p>
                                                                    Keep  the “Offer” setting on default which “Off” 
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-6.png" class="center-block" />

                                                                <p>
                                                                    Choose the city you are marketing in with a radius. We have found that the majority of buyers will come from a larger area than sellers. Adjust the radius according to your surrounding area. If you live in a heavily and densely populated area your radius might only be 10miles. If your area is more rural and/or spread out you can take your radius up higher.   
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-7.png" class="center-block" />

                                                                <!-- STEP 5 -->
                                                                <h2 class="section-title  mb-sm-40 mt-30" >
                                                                    <strong>STEP 5:</strong> DEMOGRAPHIC TARGETING 
                                                                </h2>
                                                                <p>
                                                                    In the audience name box put “Homebuyer Mistakes/Charlotte with Radius”. Add the City or area name to the ad name.Click Save.
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-8.png" class="center-block" />

                                                                <p>
                                                                    Click “Edit Placements”. Click on the arrow next to “Facebook” and UNCHECK “Right Column” and “Instant Articles”. Also UNCHECK “Audience Network”.   
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-9.png" class="center-block" />

                                                                <!-- STEP 6 -->
                                                                <h2 class="section-title  mb-sm-40 mt-30" >
                                                                    <strong>STEP 6:</strong> BUDGET AND SCHEDULE 
                                                                </h2>
                                                                <p>
                                                                    Similar to other methods of advertising, Facebook ads is dependent on budget. The more money you spend, the larger your reach (the number of people your ad is shown to). That being said, after lots of trial and error we have found $5 to $10 a day for one week is sufficient. . Remember, if things are going well, you can always add more money and extend the length of the Ad. Plan to review your results but give it time! 
                                                                </p>

                                                                <p>
                                                                    For “BUDGET” click Lifetime Budget” and enter $70.00. 
                                                                </p>

                                                                <p>
                                                                    For “SCHEDULE”, Facebook will default to “RUN MY AD CONTINUOUSLY STARTING TODAY”. Change that setting to “SET A START AND END DATE”.   
                                                                </p>

                                                                <p>
                                                                    Click on the “START ” date box and enter whatever date you want your ad to begin. Click on the time box and enter “8:00 AM”. Click on the “END” date box and enter one month from your start date. Click on the time box and enter “8:00 PM”. Double check that you have entered “AM” to start and “PM” to end. You don’t want to waste precious ad time by mixing up the two.
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-10.png" class="center-block" />

                                                                <!-- STEP 7 -->
                                                                <h2 class="section-title  mb-sm-40 mt-30" >
                                                                    <strong>STEP 7:</strong> AD DELIVERY 
                                                                </h2>

                                                                <p>
                                                                    Click Advanced Options and leave on default settings.
                                                                </p>

                                                                <p>
                                                                    For “AD SET NAME” you can leave it as is or rename it to something more specific related to your ad like “Homebuyers/Charlotte/No Targeting/Lifetime $70”. The more details you provide here the easier it will be to keep track once you have multiple ad sets and ads. Click on the blue “Continue” button to move onto the next section.   
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-11.png" class="center-block" />

                                                                <!-- STEP 8 -->
                                                                <h2 class="section-title  mb-sm-40 mt-30">
                                                                    <strong>STEP 8:</strong> AD IMAGES 
                                                                </h2>

                                                                <p>
                                                                    Leave it as “A SINGLE VIDEO OR IMAGE IN YOUR ADS” 
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-12.png" class="center-block" />

                                                                <p>
                                                                    Click on “UPLOAD IMAGES”. That will open up pictures you have stored on your computer.   
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-13.png" class="center-block" />

                                                                <p>
                                                                    We have chosen a  photo for you to use for your Homebuyer Mistakes ad. To access this photo head over to your ALG Dashboard and go to the Agent Toolbox tab. Look for the Homebuyer Mistakes photo. It is a picture of a very rundown house. 
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-14.png" class="center-block" />

                                                                <p>
                                                                    The image that will be used in the ad will be framed by a red line. Make sure it is the correct image. 
                                                                </p>

                                                                <!-- STEP 9 -->
                                                                <h2 class="section-title  mb-sm-40 mt-30" >
                                                                    <strong>STEP 9:</strong> AD IMAGES 
                                                                </h2>

                                                                <p>
                                                                    Connect your “COMMUNITY FACEBOOK PAGE” by clicking the arrow on the right. Your choices will drop down and you will choose the Page that you made SPECIFICALLY for your ads. Make sure you are NOT choosing your Facebook personal page or your Facebook business page that is associated with your name or company. 
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-15.png" class="center-block" />

                                                                <p>
                                                                    Leave the Instagram settings at the default. Facebook will automatically place your ad in the news feed of Instagram as well as Facebook. You DO NOT need to have an Instagram account to use this feature. There is no downside to using this feature. More reach always equals better results! 
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-16.png" class="center-block" />

                                                                <p>
                                                                    <!-- For the Website URL field it is very important that you input the correct URL. After all, this is where potential leads will go after they click on your ad! Remember, you will have already chosen, customized and published your List of Homs Landing page in your Agent Lead Genesis Dashboard at www.algdash.com. You will copy that same link and paste it in the Website URL field in Facebook. Facebook will test the URL to make sure it is functioning.  -->
                                                                    For the Website URL field it is very important that you input the correct URL. After all, this is where potential leads will go after they click on your ad! Remember, you will have already chosen, customized and published your List of Homs Landing page in your Dashboard at www.algdash.com. You will copy that same link and paste it in the Website URL field in Facebook. Facebook will test the URL to make sure it is functioning. 
                                                                </p>

                                                                <p>
                                                                    Leave the “Messenger” choices uncheck 
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-17.png" class="center-block" />

                                                                <p>
                                                                    For the “HEADLINE” field enter the text “Don't Be The Charlotte Homebuyer That Gets Stuck With This Home!” Remember to change the term “Charlotte” to the area you intend to target. Make sure it matches the area you used for the ad targeting and the area you used on your Homebuyer Mistakes Landing Page. 
                                                                </p>

                                                                <p>
                                                                    For the “TEXT” area enter the text “Attention Charlotte Homebuyers! Looking To Move?” Again, replace “Charlotte” with something from your area. Keep in mind the area you choose should match the area on the targeting of the ad as well as the Homebuyer Mistakes landing page. 
                                                                </p>

                                                                <p>
                                                                    Keep the “CALL TO ACTION” button as “LEARN MORE”. 
                                                                </p>

                                                                <p>
                                                                    Click on “SHOW ADVANCED OPTIONS” to show a drop down menu. Keep everything on the default settings 
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-18.png" class="center-block" />

                                                                <p>
                                                                    In the “NEWS FEED LINK DESCRIPTION” put enter the text “Get instant access to this chart sheet and learn how to avoid the most common mistakes homebuyers make.” 
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-19.png" class="center-block" />

                                                                <p>
                                                                    Facebook requires the display link to be the same as the destination website URL (where visitors are sent after they click on ad) so just copy and paste the URL destination link from earlier in the process (ex. www.algdash.com/charlotte) 
                                                                </p>

                                                                <p>
                                                                    You’re almost there! 
                                                                </p>

                                                                <p>
                                                                    As you create your ad text and image Facebook will update the right side to give you a preview of what your ad will look like.   
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-20.png" class="center-block" />

                                                                <p>
                                                                    Congratulations, you are now ready to place your Facebook Ad! 
                                                                </p>

                                                                <p>
                                                                    Double check that everything is correct and click “PLACE ORDER”.Facebook will review your ad before it is approved. 
                                                                </p>

                                                                <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer-Leads-Homebuyer-Mistakes-21.png" class="center-block" />


                                                                <h2 class="section-title mb-10 mb-sm-40 mt-30" >
                                                                    You Have a Buyer Lead! Now What? Homebuyer Mistakes Follow Up  
                                                                </h2>

                                                                <p>
                                                                    <!-- Keep in mind that you DO NOT need to send the 5 Biggest Homebuyer Mistakes Cheat Sheet to your leads. The Agent Lead Genesis System will automatically email the cheat sheet to your lead as soon as their info is submitted to the landing page. The email will contain your contact info.  -->
                                                                    Keep in mind that you DO NOT need to send the 5 Biggest Homebuyer Mistakes Cheat Sheet to your leads. The System will automatically email the cheat sheet to your lead as soon as their info is submitted to the landing page. The email will contain your contact info. 
                                                                </p>

                                                                <p>
                                                                    If you have a lead with all of the information submitted (name, email, phone number) follow up with the buyer lead as soon as possible to gather more information on their potential home purchase. You can use one or more of the following methods: 
                                                                </p>

                                                                <p>
                                                                    <div class="col-sm-4 text-center">
                                                                        <strong>- EMAIL</strong>
                                                                    </div>

                                                                    <div class="col-sm-4 text-center">
                                                                        <strong>- CALL</strong>
                                                                    </div>

                                                                    <div class="col-sm-4 text-center">
                                                                        <strong>- TEXT</strong>
                                                                    </div>
                                                                </p>

                                                                <p>
                                                                    If you are unable to make any contact with the lead you can always add them to your CRM/Newsletter list. 
                                                                </p>

                                                                <p>
                                                                    If you have a partial lead with only some of the information submitted (possibly only an email) you will need to do a little investigation to gather some more info. Remember partial leads are still super valuable! Here are a few resources to help you get some more info: 
                                                                </p>

                                                                <p class="text-center">
                                                                    www.whitepages.com (free, reverse ph.# and address lookup) 
                                                                </p>

                                                                <p class="text-center">
                                                                    www.intellius.com ($10 first month, $20 after, phone and email search) 
                                                                </p>

                                                                <p class="text-center mb-30">
                                                                    Google Search 
                                                                </p>

                                                                <p class="mb-30">
                                                                    ** Remember that every lead is sent an automatic email on your behalf asking some sort of question in an attempt to start a conversation. Most leads will not respond but don’t be surprised if they do! Either way, you still need to move forward with the full process of following up with your leads. 
                                                                </p>

                                                                <p class="mb-30">
                                                                    A word about our lead philosophy
                                                                </p>

                                                                <p>
                                                                    Try to treat every lead as incredibly valuable. Because it is! Try to respond as soon as possible and as personally as possible. You are the only one that knows your life, time commitments, and responsibilities. All of these will affect the amount of time and effort you will spend on each lead. It is really important to do YOUR best every time. Keep in mind you may get some fake names and phone numbers with these leads. It is normal and to be expected. Don’t get discouraged! Also remember that just because someone isn’t ready to sell or buy right now they may be ready 3 or 6 months down the road. You want them to remember that YOU provided something of value and followed up personally. Stick with it! 
                                                                </p>
                                                          </div>
                                                        </div>
                                                    </div>
                                                 </div>   
                                        </div>
                                        <div class="col-md-4">
                                            <div class="pdf-btn">
                                                <a href="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Buyer_Leads_Homebuyer_Mistakes.pdf" download><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/print-pdf-btn.png" class="mb-30"></a>
                                            </div>
                                            
                                        </div>
                                    </div>
                                </div>

                                
                          <!--   </div> -->

                        </div>
                        <!-- End Content -->

                    </div>
                     <div class="row">
                         <div class="col-md-6">
                             <div class="fb-btn"> 
                                 <a href="<?php echo PUBLIC_PATH?>/lead_www4/images/homebuyer_mistakes/Homebuyer_Mistakes.jpg" download><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/fb-add.png"><span>FB Ad Image</span> </a>
                             </div>
                         </div>
                         <div class="col-md-6">
                             <div class="fb-btn fl-left">
                                 <a href="#"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/Fb-post.png" ><span>Example FB Post</span> </a>
                             </div>
                         </div>
                     </div>
                    
                </div>

            </section>
 <!-- End Section -->

