 <!-- Logo Section -->
            <section class="small-section pt-30 pt-xs-20 pb-30 pb-xs-20 header-bg-color">
                
                <div class="container align-center">
                    <div class="row">
                        <div class="col-xs-8 col-xs-offset-2">
                            <a href="#">
                        </a>
                            <!-- Navigation panel -->
				            <nav class="main-nav mn-align-left not-top mt-20">
				                <div class="relative clearfix">
				                    
				                    <div class="mobile-nav">
				                        <i class="fa fa-bars"></i>
				                    </div>
				                    
				                    <!-- Main Menu -->
				                    <div class="inner-nav desktop-nav">
				                        <ul class="clearlist">
				                            <li>
				                                 <a href="<?php echo $this->baseUrl()?>/agent-lead"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/training-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">Training</div></a>
				                            </li>
				                            <li>
				                                 <a href="<?php echo $this->baseUrl()?>/agent-toolbox-lp"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/wrench-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">Agent Toolbox</div></a>  
				                            </li>
				                            
				                            <li>
				                                <a href="<?php echo $this->baseUrl()?>/profile/home"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/gear-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">ALG Dashboard</div></a>
				                            </li>
 				                        </ul>
				                    </div>
				                    <!-- End Main Menu -->
				                </div>
				            </nav>
				            <!-- End Navigation panel -->
				            <h1 class="main-heading">Guide To Seller Leads: Sell Your Home For More</h1>
                        </div>
                    </div>
                </div>  
            </section>
            <!-- End Logo Section -->

            <section class="page-section pt-30 pb-30">
                <div class="container relative">
                    
                    <div class="row">
                        
                        <!-- Sidebar -->
                        <!-- <div class="col-sm-4 col-md-3 sidebar">
                        	
	                            <a href="https://drive.google.com/file/d/0B8Lu6Or0uwT6RkJsSjI3ZlN6S28/preview" class="html5lightbox" data-width="640" data-height="480" title="ALG Dash Tutorial"><img src="<?php //echo PUBLIC_PATH?>/lead_www4/images/lead/watch-the-video-btn.png" class="mb-30"></a>
	                            <a href="<?php //echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller_Leads_Sell_Your_Home_For_Top_Dollar.pdf" download><img src="<?php //echo PUBLIC_PATH?>/lead_www4/images/lead/print-pdf-version-btn.png" class="mb-30"></a>
	                            <a href="<?php //echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Sell_Your_Home_For_Top_Dollar.jpg" download><img src="<?php //echo PUBLIC_PATH?>/lead_www4/images/lead/fb-ad-image-btn.png"></a>
                           
                        </div> -->
                        <!-- End Sidebar -->

                        <!-- Content -->
                       <div class="col-sm-12 col-md-12">
                            <div class="step1-section">
                                    <h2 class="section-title mb-10 mb-sm-40">
                                        <strong>STEP 1:</strong> Login to your personal account at https://www.facebook.com
                                    </h2>
                                 <div class="video-shadow">
                                     <div class="embed-responsive embed-responsive-16by9">
									 <iframe style="margin:0;padding:0;border:0;" id="html5lightbox-web-iframe" width="100%" height="100%" src="https://drive.google.com/file/d/0B8Lu6Or0uwT6RkJsSjI3ZlN6S28/preview" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen=""></iframe>
                                    </div>
                                 </div>   
                                  
                             </div>
                            <!-- Post Title -->
                            <div class="row">
                                    <div class="down-content">
                                        <div class="col-md-8">
                                            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                                                    <div class="panel panel-default bd-color">
                                                        <div class="panel-heading bg-color" role="tab" id="headingOne">
                                                          <h4 class="panel-title">
                                                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                                              Login to your personal account
                                                              <span><i class="fa fa-angle-down" aria-hidden="true"></i></span>
                                                            </a>
                                                          </h4>
                                                        </div>
                                                        <div id="collapseOne" class="panel-collapse collapse " role="tabpanel" aria-labelledby="headingOne">
                                                          <div class="panel-body">
                                                           <ul>
                                        <li>If you don’t already have a Facebook Community Business Page go to our step by step guide.</li>
                                        <li>If you don’t already have a Facebook personal page go to our step by step guide.</li>
                                        <li>Make sure you are using your “Community Business Page”. If you have a separate business page related directly to your Real Estate Company or brokerage DO NOT use that page.</li>
                                        <!-- <li>Use your Agent Lead Genesis dashboard to choose, create, and publish your landing page BEFORE you make your Facebook Ad.</li> -->
                                        <li>Use your dashboard to choose, create, and publish your landing page BEFORE you make your Facebook Ad.</li>
                                    </ul>

                                    <!-- STEP 1 -->
                                    
                                    <p>
                                        Click on the arrow on the top right top of your screen. Click on “CREATE ADS”.
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-1.png" class="center-block" />

                                    <!-- STEP 2 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30">
                                        <strong>STEP 2:</strong>  Choose the objective for your campaign. 
                                    </h2>
                                    <p>
                                        These first few steps will change order depending on whether it is your first time creating a new ad account or you are returning. The instructions of choosing “TRAFFIC” for the Campaign Objective and naming the Campaign remain the same.   
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-2.png" class="center-block" />

                                    <!-- STEP 3 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30">
                                        <strong>STEP 3:</strong>
                                    </h2>
                                    <p>
                                        Enter a Campaign Name in box. A Campaign Name will contain multiple ad sets and ads  within a campaign. Choose something like “Sell Your Home For More” and then your ad set within the campaign might be named “Sell Your Home For More/San Jose/No Radius/Lifetime $70”. From there you can name your ads with corresponding details to help you keep track of each ad.  
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-3.png" class="center-block" />

                                    <p>
                                        The following screen shot will only appear the FIRST time you are creating an account. Click Continue 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-4.png" class="center-block" />

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-5.png" class="center-block" />

                                    <!-- STEP 4 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30">
                                        <strong>STEP 4:</strong> LOCATION TARGETING 
                                    </h2>
                                    <p>
                                        You can target a city,  several zip codes, a county, or a area such as Tri City Area. If you choose an area larger than a city (like a county or Tri City Area) try to pick the middle point on the map and add a radius to match your desired area. If you choose a single city, Facebook will automatically add a 25 mile radius. Make sure you remove the radius by clicking on the area next to the radius and choose “Current City Only”. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-6.png" class="center-block" />

                                    <!-- STEP 5 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30">
                                        <strong>STEP 5:</strong> DEMOGRAPHIC TARGETING 
                                    </h2>
                                    <p>
                                        Choose an age range of 23-65. Choose All Genders. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-7.png" class="center-block" />

                                    <p>
                                        Under “Detailed Targeting”  type in “Homeowners”.Click on “Homeowners” in the dropdown menu. It will be in the “Demographics” category. Then, check the “SAVE THIS AUDIENCE” box.    
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-8.png" class="center-block" />

                                    <p>
                                        And, in the audience name put “Sell Your Home For More/City/Homeowners”. Add the City or area name to the ad name. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-9.png" class="center-block" />

                                    <p>
                                        Click “Edit Placements”. Click on the arrow next to “Facebook” and UNCHECK “Right Column” and “Instant Articles”. Also UNCHECK “Audience Network”.   
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-10.png" class="center-block" />

                                    <!-- STEP 6 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30">
                                        <strong>STEP 6:</strong> BUDGETING 
                                    </h2>
                                    <p>
                                        Similar to other methods of advertising, Facebook ads is dependent on budget. The more money you spend, the larger your reach (the number of people your ad is shown to). That being said, after lots of trial and error we have found $5 to $10 a day for one week is sufficient. Remember, if things are going well, you can always add more money and extend the length of the Ad, or if it’s doing poorly you can always turn off the ad. Plan to review your results but give it time!  
                                    </p>

                                    <p>
                                        For “BUDGET” click Lifetime Budget” and enter $70.00. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-11.png" class="center-block" />

                                    <p>
                                        For “SCHEDULE”, Facebook will default to “RUN MY AD CONTINUOUSLY STARTING TODAY”. Change that setting to “SET A START AND END DATE”.   
                                    </p>

                                    <p>
                                        Click on the “START ” date box and enter whatever date you want your ad to begin. Click on the time box and enter “8:00 AM”. Click on the “END” date box and enter one week from your start date. Click on the time box and enter “8:00 PM”. Double check that you have entered “AM” to start and “PM” to end. You don’t want to waste precious ad time by mixing up the two. Ignore the “Show Advanced Options” link below the “Budget &Schedule” fields. All of that info will be left on the default settings. 
                                    </p>

                                    <!-- STEP 7 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30">
                                        <strong>STEP 7:</strong> AD DELIVERY 
                                    </h2>

                                    <p>
                                        Click Advanced Options and double check your settings.
                                    </p>

                                    <p>
                                        For “AD SET NAME” you can leave it as is or rename it to something more specific related to your ad like “Sell Your Home For More/San Jose/Homeowners/Lifetime/$70”.The more details you provide here the easier it will be to keep track once you have multiple ad sets and ads. Click on the blue “Continue” button to move onto the next section.  
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-12.png" class="center-block" />

                                    <!-- STEP 8 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30">
                                        <strong>STEP 8:</strong> AD IMAGES 
                                    </h2>

                                    <p>
                                        Choose “Single Image” for the format.  
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-13.png" class="center-block" />

                                    <p>
                                        Click on “UPLOAD IMAGES”. That will open up pictures you have stored on your computer.   
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-14.png" class="center-block" />

                                    <p>
                                        We have a stock photo for you to use for your Sell Your Home For More ads. We chose something that has nice color, is eye catching, and stands out on the page. To access this photo head over to the Education section of the ALG website. The photo is in the Toolbox area. It is the Sell Your Home For More image is a little home sitting on a pile of money.  Download the image to your computer and upload when prompted on the ad.
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-15.png" class="center-block" />

                                    <p>
                                        The image that will be used in the ad will be framed by a red line. Make sure it is the correct image. 
                                    </p>

                                    <!-- STEP 9 -->
                                    <h2 class="section-title mb-10 mb-sm-40 mt-30">
                                        <strong>STEP 9:</strong> AD IMAGES 
                                    </h2>

                                    <p>
                                        Connect your “FACEBOOK BUSINESS PAGE” by clicking the arrow on the right. Your choices will drop down and you will choose the Page that you made SPECIFICALLY for your ads. Make sure you are NOT choosing your Facebook personal page or your Facebook business page that is associated with your name or company. This is the Facebook Business Page that you made centered around the community you are targeting.  
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-16.png" class="center-block" />

                                    <p>
                                        Leave the Instagram settings at the default. Facebook will automatically place your ad in the news feed of Instagram as well as Facebook. You DO NOT need to have an Instagram account to use this feature. There is no downside to using this feature. More reach always equals better results!  
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-17.png" class="center-block" />

                                    <p>
                                        <!-- or the Website URL field it is very important that you input the correct URL. After all, this is where potential leads will go after they click on your ad! Remember, you will have already chosen, customized and published your Home Value Landing page in your Agent Lead Genesis Dashboard at www.algdash.com. You will copy that same link and paste it in the Website URL field in Facebook. Facebook will test the URL to make sure it is functioning.  -->
                                        or the Website URL field it is very important that you input the correct URL. After all, this is where potential leads will go after they click on your ad! Remember, you will have already chosen, customized and published your Home Value Landing page in your Dashboard at www.algdash.com. You will copy that same link and paste it in the Website URL field in Facebook. Facebook will test the URL to make sure it is functioning. 
                                    </p>

                                    <p>
                                        Leave the “Messenger” choices unchecked. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-18.png" class="center-block" />

                                    <p>
                                        For the “HEADLINE” field enter the text “Sell Your San Jose Home For More!” Remember to change the term “San Jose” to the area you intend to target. Make sure it matches the area you used for the ad targeting and your Home Value landing page. 
                                    </p>

                                    <p>
                                        For the “TEXT” area enter the text “Get Instant Access To Your Cheat Sheet And Learn How To Sell Your San Jose Home For Top Dollar. “ Again, replace “San Jose” with something from your area. You can use a city, area (such as Tri City), or county. Keep in mind the area you choose should match the area on the targeting of the ad as well as the Home Valuelanding page.  
                                    </p>

                                    <p>
                                        Keep the “CALL TO ACTION” button as “LEARN MORE”. 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-19.png" class="center-block" />

                                    <p>
                                        Click on “SHOW ADVANCED OPTIONS” to show a drop down menu.   
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-20.png" class="center-block" />

                                    <p>
                                        In the “NEWS FEED LINK DESCRIPTION” put enter the text “This guide is full of proven strategies and tips to help you get the most money possible on your home sale. These tips are inexpensive and easy to implement.” Again, make sure that area matches with other text in the ad as well as the targeting and landing page.
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-21.png" class="center-block" />

                                    <p>
                                        Facebook requires the display link to be the same as the destination website URL (where visitors are sent after they click on ad) so just copy and paste the URL destination link from earlier in the process (ex. www.algdash.com/sanjose) 
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-22.png" class="center-block" />

                                    <p>
                                        As you create your ad text and image Facebook will update the right side to give you a preview of what your ad will look like.
                                    </p>

                                    <p>
                                        Double check the details of your ad and then click Place Order. Facebook will review your ad before placement.    
                                    </p>

                                    <img src="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller-Leads-Sell-Your-Home-For-Top-Dollar-23.png" class="center-block" />


                                    <h2 class="section-title mb-10 mb-sm-40 mt-30" >
                                        You Have a New Seller Lead! Now What? Sell Your Home for Top Dollar Follow Up 
                                    </h2>

                                    <p>
                                        <!-- Remember you DO NOT need to send the Sell Your Home for Top Dollar Cheat Sheet to your lead. The Agent Lead Genesis System will automatically email the cheat sheet to your lead right after the information is submitted to the landing page. Remember to follow up as soon as possible!  -->
                                        Remember you DO NOT need to send the Sell Your Home for Top Dollar Cheat Sheet to your lead. The System will automatically email the cheat sheet to your lead right after the information is submitted to the landing page. Remember to follow up as soon as possible! 
                                    </p>

                                    <p>
                                        On this landing page both name and email are required fields. People will typically put in a correct email so they can get the lead magnet. You may get some fake names but keep in mind it’s part of the process and totally expected. 
                                    </p>

                                    <p>
                                        Try to make contact with the lead to find out more information about their potential home sale via email
                                    </p>

                                    <p>
                                        You can also use the information you have to gather some additional information like phone number and address (this is the most valuable as it opens up in person or direct mail opportunities).  You can try a few different methods.   
                                    </p>

                                    <p class="text-center">
                                        www.whitepages.com (free, reverse ph. # and address lookup)
                                    </p>

                                    <p class="text-center">
                                        www.intellius.com ($10 first mo. Then $20 per mo. Phone and email search) 
                                    </p>

                                    <p class="text-center">
                                        MLS (use name to find an address of record) 
                                    </p>

                                    <p class="text-center">
                                       Google Search  
                                    </p>

                                    <p>
                                        Keep in mind these systems are not perfect. You may find outdated phone numbers, several addresses, etc. But it’s a start!
                                    </p>

                                    <p>
                                        With the information you have gathered try to make contact  in one or more of the following ways: 
                                    </p>

                                    <p>
                                        <div class="col-sm-3 text-center">
                                            <strong>- Phone Call</strong>
                                        </div>

                                        <div class="col-sm-3 text-center">
                                            <strong>- Text</strong>
                                        </div>

                                        <div class="col-sm-3 text-center">
                                            <strong>- Direct Mail**</strong>
                                        </div>

                                        <div class="col-sm-3 text-center">
                                            <strong>- Email</strong>
                                        </div>
                                    </p>

                                    <p>
                                        If there is no response you can add lead to your Email/Newsletter system and/or your direct mail campaign
                                    </p>

                                    <p>
                                        ** Remember that every lead is sent an automatic email on your behalf asking some sort of question in an attempt to start a conversation. Most leads will not respond but don’t be surprised if they do! Either way, you still need to move forward with the full process of following up with your leads.   
                                    </p>

                                    <p class="mb-30">
                                        A word about our lead philosophy
                                    </p>

                                    <p>
                                        Try to treat every lead as incredibly valuable. Because it is! Try to respond as soon as possible and as personally as possible. You are the only one that knows your life, time commitments, and responsibilities. All of these will affect the amount of time and effort you will spend on each lead. It is really important to do YOUR best every time.   
                                    </p>

                                    <p>
                                        Keep in mind you may get some fake names and phone numbers with these leads. It is normal and to be expected. Don’t get discouraged! Also remember that just because someone isn’t ready to sell or buy right now they may be ready 3 or 6 months down the road. You want them to remember that YOU provided something of value and followed up personally. Stick with it!   
                                    </p>
                                                          </div>
                                                        </div>
                                                    </div>
                                                 </div>   
                                        </div>
                                        <div class="col-md-4">
                                            <div class="pdf-btn">
                                                <a href="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Seller_Leads_Sell_Your_Home_For_Top_Dollar.pdf" download=""><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/print-pdf-btn.png" class="mb-30"></a>
                                            </div>
                                            
                                        </div>
                                    </div>
                                </div>

                        <!-- End Content -->
                        <div class="row">
                         <div class="col-md-6">
                             <div class="fb-btn">
                                 
                                 <a href="<?php echo PUBLIC_PATH?>/lead_www4/images/sell_your_home_for_top_dollar/Sell_Your_Home_For_Top_Dollar.jpg" download=""><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/fb-add.png"><span>FB Ad Image</span></a>
                             </div>
                         </div>
                         <div class="col-md-6">
                             <div class="fb-btn fl-left">
                                 <!-- <a href=" https://drive.google.com/file/d/0B8Lu6Or0uwT6Z2FGLXdkOUtSLXM/preview" class="html5lightbox" data-width="640" data-height="480" title="ALG Dash Tutorial"> --><a href="#"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/Fb-post.png" ><span>Example FB Post</span> </a><!-- </a> -->
                             </div>
                         </div>
                     </div>
                    </div>
                        <!-- End Content -->

                    </div>

                </div>

            </section>
            <!-- End Section -->