<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" >
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>

<?php 
	echo $this->headMeta();
	echo $this->headTitle('Admin Login');
	echo $this->headLink();
?>

<script> var baseUrl = '<?php echo APPLICATION_URL?>';</script>

</head>
<!-- END HEAD -->


<!-- BEGIN BODY -->
<body class="login">

	<!-- BEGIN LOGO -->
	<div class="page-logo text-center logo" style="margin-top:12px;">
		<a >
		<?php echo $this->site_configs['site_title']?>	
		</a>
	</div>
	<!-- END LOGO -->
	
	
	<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
	<div class="menu-toggler sidebar-toggler"></div>
	<!-- END SIDEBAR TOGGLER BUTTON -->
	
	
	<!-- BEGIN LOGIN -->
	<div class="content">
	
		<?php echo $this->getHelper("Messages")->getMessages();?>
		<!-- BEGIN LOGIN FORM -->
		<form class="login-form profile_form"   method="post">
			<h3 class="form-title">RESET PASSWORD</h3>
			
			<div class="form-group">
				<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
				<label class="control-label visible-ie8 visible-ie9">Password</label>
				<div class="input-icon">
					<?php echo $this->form->user_password?>
				</div>
			</div>
			<div class="form-group">
				<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
				<label class="control-label visible-ie8 visible-ie9">Confirm Password</label>
				<div class="input-icon">
					<?php echo $this->form->user_rpassword?>
				</div>
			</div>
			<div class="form-actions">
				 <?php echo $this->form->submit  ?>
				<!--<button type="submit" class="btn blue pull-right"> Login <i class="m-icon-swapright m-icon-white"></i> </button>-->
                
                <a  style="color:#fff" href="<?php echo SITE_HTTP_URL ?>/privatepanel"><?php echo 'Login'; ?></a>
                <br/>
			</div>
		</form>
		<!-- END LOGIN FORM -->
	</div>
	<!-- END LOGIN -->
	
	<!-- BEGIN COPYRIGHT -->
	<div class="copyright">
		 <?=date('Y')?> &copy; 
		<?php echo $this->site_configs['site_title'];?> 
	</div>


	<?php echo $this->headScript(); // Javascript?>


	<script type="application/javascript">
	jQuery(document).ready(function() {     
		Metronic.init(); // init metronic core components
		Login.init();
	});
	</script>
</body>
</html>