 <!-- Logo Section -->
            <section class="small-section pt-30 pt-xs-20 pb-30 pb-xs-20" style="background-color: #0069ff;">
                
                <div class="container align-center">
                    <div class="row">
                        <div class="col-xs-8 col-xs-offset-2">
                            <a href="#"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/logo.png" alt="" /></a>
                            <!-- Navigation panel -->
				            <nav class="main-nav mn-align-left not-top mt-20">
				                <div class="relative clearfix">
				                    
				                    <div class="mobile-nav">
				                        <i class="fa fa-bars"></i>
				                    </div>
				                    
				                    <!-- Main Menu -->
				                    <div class="inner-nav desktop-nav">
				                        <ul class="clearlist">
				                            <li>
				                                 <a href="<?php echo $this->baseUrl()?>/agent-lead"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/training-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">Training</div></a>
				                            </li>
				                            <li>
				                                 <a href="<?php echo $this->baseUrl()?>/agent-toolbox-lp"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/wrench-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">Agent Toolbox</div></a>  
				                            </li>
				                            
				                            <li>
				                                <a href="<?php echo $this->baseUrl()?>/profile/home"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/gear-icon.png" style="display: inline-block; margin-right: 5px" /><div style="top: 0px; position: relative; display: inline-block;">ALG Dashboard</div></a>
				                            </li>
 				                        </ul>
				                    </div>
				                    <!-- End Main Menu -->
				                </div>
				            </nav>
				            <!-- End Navigation panel -->
				            <h1 style="margin-bottom: 0; font-weight: bold; color: white; text-transform: uppercase;">Guide To Banner Ads</h1>
                        </div>
                    </div>
                </div>  
            </section>
            <!-- End Logo Section -->

            <section class="page-section pt-30 pb-30">
                <div class="container relative">
                    
                    <div class="row">
                        
                        <!-- Sidebar -->
                        <div class="col-sm-4 col-md-3 sidebar">
                        	
	                            <a href="https://drive.google.com/file/d/0B8Lu6Or0uwT6aVh3MV85YW95cE0/preview" class="html5lightbox" data-width="640" data-height="480" title="ALG Dash Tutorial"><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/watch-the-video-btn.png" class="mb-30"></a>
                                <a href="<?php echo PUBLIC_PATH?>/lead_www4/images/banner_images/bannerads.zip" download><img src="<?php echo PUBLIC_PATH?>/lead_www4/images/lead/banner-image-btn.png"></a>
                           
                        </div>
                        <!-- End Sidebar -->

                        <!-- Content -->
                        <div class="col-sm-8">

                            <!-- Post Title -->
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    
                                    <iframe src="https://drive.google.com/file/d/0B8Lu6Or0uwT6aVh3MV85YW95cE0/preview" width="640" height="480"></iframe>

                                </div>
                            </div>

                        </div>
                        <!-- End Content -->

                    </div>

                </div>

            </section>
            <!-- End Section -->